### PR TITLE
add basic fuzzers

### PR DESCRIPTION
**Pull request by pauldreik**
I ran these for a while without any problem, after #345 was fixed.

They are default off, so should not bother anyone.

If there is any interest, I can add continuous integration in another pull request which runs the corpus on pull requests, as recommended by fuzzing best practices.

See https://github.com/lemire/simdjson/issues/345#issuecomment-546108944 for some comments which may be of interest.

### CODE REVIEW

**Comment by lemire** [comment]
Looks good to me, let us see what the tests reveal.

**Comment by pauldreik** [comment]
@lemire, are you ok with merging this branch, or is there something more that needs to be fixed first?

**Comment by lemire** [comment]
Merging.

I'll check that your name appears.

**Comment by lemire** [comment]
https://github.com/lemire/simdjson/blob/master/CONTRIBUTORS

**Pull request merged**
