### PR TITLE
Minor tweaks on fallback.

### PR DESCRIPTION
**Pull request by lemire**
Minor tweaks that most have to do with documentation.

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser This is to merge in your PR, not master.

**Comment by lemire** [comment]
Mostly I think we need to update the documentation... @jkeiser  you should read over what I wrote in the README to make sure it matches your expectations.

**Comment by jkeiser** [comment]
I merged this in. We should consider whether to open up the ARM side of this too--there's at least no reason why the fallback won't work there, too. I haven't spent enough time with ARM processors to understand the ramifications of removing that flag from the Makefile, though.

**Comment by lemire** [comment]
> We should consider whether to open up the ARM side of this too--there's at least no reason why the fallback won't work there, too. I haven't spent enough time with ARM processors to understand the ramifications of removing that flag from the Makefile, though.

I will remove the flag in a separate PR. I don't think it is necessary.

**Pull request closed without merging**
