### PR TITLE
use unique_ptr in class parsedjson

### PR DESCRIPTION
**Pull request by pauldreik**
This switches from owning raw pointers to use unique_ptr.

This simplifies the code.

Background:
 - https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-raii
 - https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-ptr
 - https://en.cppreference.com/w/cpp/language/rule_of_three

### CODE REVIEW

**Comment by lemire** [comment]
Sure. You are trimming the line count, always a good sign.

On a related note, you have at least identified one construct is cause for concern:

```C
tape[current_loc++] = *(reinterpret_cast<uint64_t *>(&i));
```

I am not sure that this is safe as per the language specification.

It would be better to do...
```C
memcpy(tape + current_loc , &i, size(i));
current_loc++;
```

**Comment by pauldreik** [comment]
> Sure. You are trimming the line count, always a good sign.
> 
> On a related note, you have at least identified one construct is cause for concern:
> 
> ```c
> tape[current_loc++] = *(reinterpret_cast<uint64_t *>(&i));
> ```
> 
> I am not sure that this is safe as per the language specification.
> 
> It would be better to do...
> 
> ```c
> memcpy(tape + current_loc , &i, size(i));
> current_loc++;
> ```

Oh, I see I missed the * in front when I made that drive-by comment! Your fix looks good. I will add it and merge.

**Comment by pauldreik** [comment]
Hmm, the drone checkperf reports a perf loss now with the last fix. Is it accurate? I do not want to merge with a failed CI build.

**Comment by lemire** [comment]
@pauldreik The perf tests are more of a warning. When this happens you want to examine the performance to make sure there is no regression.

**Comment by pauldreik** [comment]
This is very interesting. When I run locally, on a i7-8565U laptop with gcc 8.3, I get the following

gsoc gets faster:
```sh
scripts/checkperf.sh master jsonexamples/gsoc-2018.json
The new code has a throughput in       3.38774 -- 4.00801
The reference code has a throughput in 3.1928 -- 3.96302
```

twitter seems to get slower:
```sh
scripts/checkperf.sh master jsonexamples/twitter.json
The new code has a throughput in       2.51199 -- 2.6938
The reference code has a throughput in 2.69197 -- 2.73889
```

I tried to bisect this, but will give up for now. It would be interesting to understand what happens - it may be to a number of factors. The amount of inlining needed increases with the unique_ptr approach, and the noexcept situation may change. Also, when defaulting member functions the code shifts around and those seemingly unrelated changes may end up affecting performance.

**Comment by lemire** [comment]
I have checked manually the performance difference. On 64-bit ARM, the instruction counts are pretty much the same (+/-0.1 instruction per block). On x64, the instruction counts vary more (+/- 0.1 per structural character). If the direction of the change was always the same, I'd want to investigate but as pointed out by @jkeiser, sometimes we win, sometimes we lose.

Though I could be wrong with this, it seems that whether we win or not depends a bit on the size of the file: this PR helps us a tiny bit on larger inputs, but harms us a tiny bit on tiny inputs. Maybe this is wrong, but it is one model. 

This code is clearly better, simpler, more maintainable... So let us merge!

**Pull request merged**
