### PR TITLE
[WIP] range utf-8 validation for neon

### PR DESCRIPTION
**Pull request by ioioioio**
I plugged the [range-neon algorithm](https://github.com/cyb70289/utf8) so we can compare the performances. 

The author claims the difference should be more interesting on neon than on sse. In our case, it seems like the [sse version](https://github.com/lemire/simdjson/pull/279) was more interesting.

before:
./parse jsonexamples/twitter.json 
number of iterations 1000 
number of bytes 631515 number of structural chars 55264 ratio 0.088
mem alloc instructions:       1161 cycles:       4614 (0.08 %) ins/cycles: 0.25 mis. branches:         10 (cycles/mis.branch 439.18) cache accesses:     193107 (failure         23)
 mem alloc runs at 0.01 cycles per input byte.
stage 1 instructions:    2287934 cycles:    3359278 (58.47 %) ins/cycles: 0.68 mis. branches:       3255 (cycles/mis.branch 1031.93) cache accesses:     193107 (failure       9891)
 stage 1 runs at 5.32 cycles per input byte.
stage 2 instructions:    1996854 cycles:    2381678 (41.45 %) ins/cycles: 0.84 mis. branches:      13664  (cycles/mis.branch 174.29)  cache accesses:     920785 (failure      14893)
 stage 2 runs at 3.77 cycles per input byte and 43.10 cycles per structural character.
 all stages: 9.10 cycles per input byte.
Estimated average frequency: 3.218 GHz.
Min:  0.00178533 bytes read: 631515 Gigabytes/second: 0.353724

range-neon:
./parse jsonexamples/twitter.json
number of iterations 1000 
number of bytes 631515 number of structural chars 55264 ratio 0.088
mem alloc instructions:       1161 cycles:       5090 (0.09 %) ins/cycles: 0.23 mis. branches:          8 (cycles/mis.branch 629.02) cache accesses:     332883 (failure         23)
 mem alloc runs at 0.01 cycles per input byte.
stage 1 instructions:    2281578 cycles:    3316961 (59.13 %) ins/cycles: 0.69 mis. branches:       3261 (cycles/mis.branch 1016.90) cache accesses:     332883 (failure       9900)
 stage 1 runs at 5.25 cycles per input byte.
stage 2 instructions:    1996854 cycles:    2287669 (40.78 %) ins/cycles: 0.87 mis. branches:      13551  (cycles/mis.branch 168.82)  cache accesses:     920748 (failure      14902)
 stage 2 runs at 3.62 cycles per input byte and 41.40 cycles per structural character.
 all stages: 8.88 cycles per input byte.
Estimated average frequency: 3.215 GHz.
Min:  0.00174476 bytes read: 631515 Gigabytes/second: 0.36195

edit: this should be a draft pr.

### CODE REVIEW

**Comment by lemire** [comment]
Looks like a barely noticeable performance bump. What are the numbers on random.json?

**Comment by lemire** [comment]
(BTW thanks @ioioioio.)

**Comment by ioioioio** [comment]
before:
./parse jsonexamples/random.json
number of iterations 1000 
number of bytes 510476 number of structural chars 88018 ratio 0.172
mem alloc instructions:       1161 cycles:       4478 (0.06 %) ins/cycles: 0.26 mis. branches:          9 (cycles/mis.branch 493.80) cache accesses:     220604 (failure         22)
mem alloc runs at 0.01 cycles per input byte.
stage 1 instructions:    2613625 cycles:    3869380 (54.60 %) ins/cycles: 0.68 mis. branches:       3974 (cycles/mis.branch 973.52) cache accesses:     220604 (failure       7999)
 stage 1 runs at 7.58 cycles per input byte.
stage 2 instructions:    3122133 cycles:    3212815 (45.34 %) ins/cycles: 0.97 mis. branches:       4626  (cycles/mis.branch 694.48)  cache accesses:    1389410 (failure      17955)
 stage 2 runs at 6.29 cycles per input byte and 36.50 cycles per structural character.

range-neon:
./parse jsonexamples/random.json
number of iterations 1000 
number of bytes 510476 number of structural chars 88018 ratio 0.172
mem alloc instructions:       1161 cycles:       4851 (0.07 %) ins/cycles: 0.24 mis. branches:          9 (cycles/mis.branch 523.44) cache accesses:     536327 (failure         22)
 mem alloc runs at 0.01 cycles per input byte.
stage 1 instructions:    2596859 cycles:    3727573 (54.81 %) ins/cycles: 0.70 mis. branches:       3976 (cycles/mis.branch 937.31) cache accesses:     536327 (failure       8004)
 stage 1 runs at 7.30 cycles per input byte.
stage 2 instructions:    3122133 cycles:    3068638 (45.12 %) ins/cycles: 1.02 mis. branches:       4930  (cycles/mis.branch 622.36)  cache accesses:    1390255 (failure      18059)
 stage 2 runs at 6.01 cycles per input byte and 34.86 cycles per structural character.
 all stages: 13.32 cycles per input byte.
Estimated average frequency: 3.222 GHz.
Min:  0.00211106 bytes read: 510476 Gigabytes/second: 0.24181
 all stages: 13.88 cycles per input byte.
Estimated average frequency: 3.208 GHz.
Min:  0.00220906 bytes read: 510476 Gigabytes/second: 0.231083

**Comment by lemire** [comment]
A tiny gain. Still. Reviewing this PR is on our todo, we may yet gain something out of this.

**Comment by lemire** [comment]
@ioioioio It is correct now?

**Comment by lemire** [comment]
:-)

**Comment by ioioioio** [comment]
Well, this is just the modification I made on the sse version.

I am trying since yesterday to run a "asciipath" version with the [tests](https://github.com/cyb70289/utf8/blob/master/main.c) to be sure what I'm doing makes sense. However I have not been very successful. I thought it would be fast and easy :(

**Comment by ioioioio** [comment]
Well, the [asciipath](https://github.com/ioioioio/utf8/tree/range_sse_asciipath) still does not work, but I think I've spent enough time on this.

I ran more tests with the fuzzer, I've (temporarily) tweaked the json generator to generate only ascii, and I've never found any problem. So I suppose we can be confident the validation works properly.

**Comment by lemire** [comment]
+1

**Comment by jkeiser** [comment]
@ioioio @lemire When I [use this exact utf8 check code](https://github.com/lemire/simdjson/compare/jkeiser/utf8_range_arm?expand=1) in master, [ARM slows down](https://cloud.drone.io/lemire/simdjson/1444/6/2) on CI, even if I use the [old simd_input code](https://cloud.drone.io/lemire/simdjson/1446/6/2) instead of simd. Re-running this PR against master [passes but the results seem all over the place](https://cloud.drone.io/lemire/simdjson/1444/6/2). Is it possible this patch is actually slower but the perf tests were more consistent the PR was made? Or maybe I'm getting bad luck on the machines I'm running.

**Comment by jkeiser** [comment]
checkperf fails on this patch before genericization, too: [jkeiser/neon_range branch](https://github.com/lemire/simdjson/commit/97ccd09e1ba3df3562cd13fe07e94eabdfec610d) has this change, updated to latest master just *before* the simd genericization. It fails [CI perf check](https://cloud.drone.io/lemire/simdjson/1447/6/2) on ARM as well. Something changed in the interim to make this patch have a negative effect. (Maybe the refactoring of the stage 1 loop?)

**Comment by jkeiser** [comment]
OK, it has nothing to do with any intervening patch to the code, it's the way we're running the tests. If I start from this branch (no rebase), and just modify Drone so that it runs *only* checkperf and no other tests, [this patch causes a large regression on the CI machine](https://cloud.drone.io/lemire/simdjson/1452/1/2).

**Comment by jkeiser** [comment]
That's as far as I can go for now.

It's quite possible this gets slower because a different CI machine is chosen for this shorter job.  @lemire @ioioioio the [CI machine in question](https://cloud.drone.io/lemire/simdjson/1427/6/2) has `/proc;/cpuinfo` like this, which appears to be a [Cavium ThunderX CN8890](https://en.wikichip.org/wiki/cavium/thunderx/cn8890):

```
processor	: 0
--
3 | BogoMIPS	: 200.00
4 | Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
5 | CPU implementer	: 0x43
6 | CPU architecture: 8
7 | CPU variant	: 0x1
8 | CPU part	: 0x0a1
9 | CPU revision	: 1
```

Maybe you have some ideas how to track it down :)

**Comment by lemire** [comment]
Thank you. 

I have a few ARM machines that I can use for tests... but I wish we had a clean way to setup CI on them... (surely possible, but maybe time consuming)

**Comment by lemire** [comment]
Made obsolete by https://github.com/lemire/simdjson/pull/365

**Comment by jkeiser** [comment]
Since this branch is part of the PR, we will still be able to reach this code; deleting the branch so we have fewer branches to look at locally :)

**Comment by lemire** [comment]
Good.

**Pull request closed without merging**
