### PR TITLE
If we are going to have a google benchmark flag, we better make sure …

### PR DESCRIPTION
**Pull request by lemire**
…that we test it out minimally (it should build).

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser Do we want to genuinely support SIMDJSON_GOOGLE_BENCHMARKS=ON? If so, then I suggest we include it in CI. Currently, it is broken.

**Comment by jkeiser** [comment]
I think we do want it, at least until/unless we convert the tiny benchmarks I've been making to something else. I'll see why it's failing; it's been Working On My Machine (TM) :)

**Comment by jkeiser** [comment]
@lemire to check, does it build on *your* machine?

**Comment by jkeiser** [comment]
Oh hey, it looks like I broke it. Never mind.

**Comment by jkeiser** [comment]
Aha. This is likely an issue of me merging two separate patches (the simdjson.h one and the bench_dom_api one) without testing the two *together*.

**Comment by jkeiser** [comment]
@lemire should be fixed, watching CI. Note: I rebased against master and force pushed, having already forgotten that this is your branch and not mine ... so you'll need to `git remote update && git reset --hard origin/dlemire/add_google_benchmarks_to_ci` to pull this one down if you want it. (Or however you normally deal with force pushes, this is just in case you don't deal with them often.)

**Comment by lemire** [comment]
@jkeiser That's fine. Let us see if it passes.... that's all I care about.

**Comment by jkeiser** [comment]
It passed :)

**Comment by lemire** [comment]
Ok. Thanks. Given that it should not interfere with anything else, I will merge it right now.

**Pull request merged**
