### PR TITLE
[WIP] Use range check algorithm per @ioioioio

### PR DESCRIPTION
**Pull request by jkeiser**
This is the generic version of the range check algorithm proposed by @ioioioio.

Marking this draft because I'd like to fix up comments and link to the origin user, but making a PR will let me see if Circle CI succeeds.

### CODE REVIEW

**Comment by jkeiser** [comment]
@ioioioio please feel absolutely free to take this up if you wish--it'd take you way less time to consolidate the comments and such. I put this up because I felt guilty about invalidating your code when I genericized the world.

@aqrit I am pretty convinced your ideas will make this even better, but perfect and good say we should check in what we have and tinker from there :) Nonetheless, if you want to take up making some of it and make this even better, I'd be mighty obliged!

**Comment by jkeiser** [comment]
Weird, ARM seems to be slower in the two runs here, even though [this run](https://cloud.drone.io/lemire/simdjson/1386/6/2) from before genericization was merged seemed to show an improvement.

**Comment by jkeiser** [comment]
Given that this was derived from the Haswell version of @ioioioio's PR, it's possible the ARM version does something different. Still weird that it flipped without the code flipping.

**Comment by jkeiser** [comment]
Per #282, the Neon version of this patch causes perf regression even before genericization.

**Comment by lemire** [comment]
Made obsolete by https://github.com/lemire/simdjson/pull/365

**Pull request closed without merging**
