### PR TITLE
 Fix CRLF line terminators

### PR DESCRIPTION
**Pull request by mr700**
This converts the line terminators from CRLF to LF in two files (one auto-generated).

### CODE REVIEW

**Comment by lemire** [comment]
Can you sync with master once more, and only include changes in 
include/simdjson/common_defs.h. The other one is automatically generated and not meant to be edited so I don't think we should worry about line endings.

**Comment by lemire** [comment]
(Someone else must have modified include/simdjson/common_defs.h between the moment you did your work and me getting around to checking the PR.)

**Comment by mr700** [comment]
There is no longer need to do it, it is already fixed in your branch...

**Comment by lemire** [comment]
Sorry about that. I think that all I did was to add  https://github.com/lemire/simdjson/blob/master/.gitattributes

This seems to have magically resolved the issue.

**Pull request closed without merging**
