### PR TITLE
Combined performance patch (5% overall, 15% stage 1)

### PR DESCRIPTION
**Pull request by jkeiser**
This brings together all of the performance patches except [aligned loads](https://github.com/lemire/simdjson/pull/315), and even does the loop unrolling a little better (interleaving the two iterations for another 1-2% boost or so). All performance impacts are understood (at least, I have a story that purports to explain them :)) and the reordering in particular is explained in code comments.

Across all files (see [comment below](https://github.com/lemire/simdjson/pull/317#issuecomment-534256380)), it gives a 5% overall throughput improvement on average on my AVX2 Kady Lake R processor, or 1-9% improvement depending largely on the density of json elements in the file. Stage 1's improvement is 11-20%, averaging around 15%. Each of the individual patches was confirmed to have a positive performance impact on all supported architectures, so it *ought* to be fine as a combination patch as well.

This subsumes these patches, which can be reviewed individually:
- [Mark branches as likely/unlikely](https://github.com/lemire/simdjson/pull/316)
- [Decrease data dependencies in find_structurals](https://github.com/lemire/simdjson/pull/314)
- [Simplify and optimize flatten_bits](https://github.com/lemire/simdjson/pull/313)

It includes the basic ideas in [Unroll loop and reorder find_structural_bits](https://github.com/lemire/simdjson/pull/310) as well, but substantially revises them and interleaves the two iterations, roughly doubling the throughput improvement gain of the original patch. Ordering, unrolling and interleaving are not something that should be done in isolation, because they are pretty sensitive to the performance of the individual elements we're reordering, and some critical ones had performance substantially changed in the other patches.

I think there is a further improvement to do, now that I've understood all this--specifically, I think a pipelined design will maximize throughput and minimize the need for weird reordering like this--but I don't want to hold this up, there's a lot of hygienic changes as well as performance here.

It's your choice whether you'd like to review the patches separately or together; I fully understand the difficulty of reviewing uberpatches :) This actually descends from those submits, so if you go the piecemeal direction it won't be much work for me to resubmit just the loop and reorder changes afterwards.

### CODE REVIEW

**Comment by jkeiser** [comment]
I wrote some tools to use `llvm-mca` effectively, helping to see the shape of the final code and how the interleaving. I'd like to make it a graph but haven't got around to it. Here is the ASCII art instead :)

This is a graph of a single 96-cycle iteration of `find_structural_bits`. Each character from left to right represents a cycle, and the number is the number of instructions in `executing` state during that cycle according to llvm-mca. I sifted out the assembly instructions for different sections, so we could see how many instructions from each stage, and each input, are running at a given time, and get a sense of the actual parallelism.

```
find_structural_bits_128    : |455555775455555454444446766566766565445566764567768a98776665766567679797788873211111111111111 |
|- simd_input               : |234444421 |                                                                                       
|  |- 1                     : |2222222 |                                                                                         
|  |- 2                     :  |12222221 |
|                           :
|- middle                   : |22111135445555545444444676656676656544555675333322233222112111 |                                  
|  |- 1                     : |22111135445554545344343554333332222231211121 |                                                    
|  |- 2                     :              |1   1  1 1122323344434313344554333322233222112111 |                                  
|                           :
|- end                      :                                      |   1  11234546766555544656567679797788873211111111111111 |   
   |- 1                     :                                      |   1  11234546766555544542222211121111111 |                  
   |- 2                     :                                                           |  114345468676677762211111111111111 |   

Key:
- First | = The first | is the point where an instruction from that stage is decoded
- Last | = The last | is the point where the last instruction from that stage is retired
- simd_input = load JSON into
- middle = find_structurals and find_strings
- end = utf8 check, flatten
- 1 = first input
- 2 = second input
```

After separating out the assembly code for each individual function, the graph shows how they are interleaved as well.

```
find_structural_bits_128   :  |455555775455555454444446766566766565445566764567768a98776665766567679797788873211111111111111 |
|- simd_input               : |234444421 |                                                                                       
|  |- 1                     : |2222222 |                                                                                         
|  |                        :
|  |- 2                     :  |12222221 |
|                           :
|- middle                   : |22111135445555545444444676656676656544555675333322233222112111 |                                  
|  |- 1                     : |22111135445554545344343554333332222231211121 |                                                    
|  |  |- find_strings       : |2211113513444343423422122211111111112121112 |                                                     
|  |  |                     :
|  |  |- find_structurals   :   |      31111111111 12233222222111111      1 |                                                    
|  |                        :
|  |- 2                     :              |1   1  1 1122323344434313344554333322233222112111 |                                  
|     |- find_strings       :                  |1  1 112232333333221232222111111111111111211 |
|     |                     :
|     |- find_structurals   :              |1                111 21 1 22333222211122111     1 |                                  
|                           :
|- end                      :                                      |   1  11234546766555544656567679797788873211111111111111 |   
   |- 1                     :                                      |   1  11234546766555544542222211121111111 |                  
   |  |- unescaped          :                                      |   1  111    11111111     |                                  
   |  |                     :
   |  |- utf8_checker       :                                          |    1322222111    111111111111 |                         
   |  |                     :
   |  |- flatten_bits       :                                               | 232344434444341        11111111 |                  
   |  |                     :
   |  |- tail               :                                                           |   211111            |                  
   |                        :
   |- 2                     :                                                           |  114345468676677762211111111111111 |   
      |- unescaped          :                                                           |  112122111          |                  
      |                     :
      |- utf8_checker       :                                                             |  222333322211111  |                  
      |                     :
      |- flatten_bits       :                                                                |    2445456653221111111 |          
      |                     :
      |- tail               :                                                                           | 12         1111111 |   

Key:
- First | = The first | is the point where an instruction from that stage is decoded
- Last | = The last | is the point where the last instruction from that stage is retired
- simd_input = load JSON into
- middle = find_structurals and find_strings
- end = utf8 check, flatten
- 1 = first input
- 2 = second input
```

A few insights to be drawn from this:

* Because of the way most functions are written, they are wide at the beginning and narrow at the end: almost any function ends up running most of its instructions all at once, with a single critical path sticking out at the end.
* `find_structurals` and `find_strings` run almost fully in parallel, finishing at nearly the same time. find_structurals is the smaller of the pair, explaining why it's better to run it *after* find_strings. It soaks up the CPU effectively, smearing itself out (running longer than it normally would) but ultimately finishing not long before find_structurals does. This is ideal, since the output from both of these functions is required to calculate the final structurals information, and this means very little time spent waiting for one function or the other to do its part.
* The second `find_structurals` is clearing showing its dependency on the first one. There may be some optimization we can do to use the overflow from the first `find_structurals` later in the function. `find_strings` does not show this pattern.
* There is a surprising, clear line where the find structurals/strings finishes on an input, and utf8/flatten_bits begins. It seems like a coincidence because there is no data dependency between them, and the CPU is definitely fully saturated at that point.
* utf8 check/flatten_bits are showing weird "gaps" that usually indicate dependency. It could be resource contention, or it could be a dependency we hadn't realized. To be investigated ...
* That final tail indicates a pure critical path issue. It's probably ameliorated by the second loop running, I imagine.

**Comment by jkeiser** [comment]
I see a range of about 9-20% improvement in stage 1 (1-8% total improvement) across all our jsonexamples files on AVX2 Kady Lake R:

* 9-12% improvement: [random.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/random.json), [mesh.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/mesh.json), [marine_ik.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/marine_ik.json), [canada.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/canada.json). With the exception of random.json, arrays with lots of numbers are the big factor here. I can't think how that would affect stage 1 except perhaps more flattening > 8. I'm betting random has to do with containing actual utf8.
* 13-16% improvement: [twitter.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/twitter.json), [twitterescaped.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/twitterescaped.json), [citm_catalog.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/citm_catalog.json), [github_events.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/github_events.json), [mesh.pretty.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/mesh.pretty.json).
* 17-20% improvement: [gsoc-2018.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/gsoc-2018.json), [numbers.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/numbers.json), [apache_builds.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/apache_builds.json), [instruments.json](https://raw.githubusercontent.com/lemire/simdjson/master/jsonexamples/instruments.json). These all have long strings and plenty of whitespace.

Conclusion:

1. The benefit here is highly inversely correlated with the number of structurals.
2. Actual utf8 checking is a high cost!

Both of these might have implications for future optimization. I'm not 100% sure what they *mean* yet, but it's not necessary to figure that out for this patch.

**Comment by lemire** [comment]
Fantastic work.

**Comment by jkeiser** [comment]
A note: when I went back through each part of this patch to ensure it increased performance at each step (that I wasn't hiding a bad change behind a super good one), I discovered that [this change to nest `flatten_bits` if statements](https://github.com/lemire/simdjson/pull/317/commits/0b5d1d0aac8aed40c9d98e1299247c5097e1d1ae) has a slight *negative* effect if you apply it *before* the reordering/interleaving patch, and a massive *positive* effect *after* (in the place where it is now). Since I tuned the loop unroll/interleave with the nested if already in my tree, it's possible the patch is overfit to that scenario. Ergo, it's possible that if one retuned and reordered *without* the nested if in place, even more performance could be found.

I don't intend to look at it now. Tuning with the `if` is plenty kickass, for all platforms. But it's in the back of my mind for later.

**Comment by lemire** [comment]
+1

**Comment by jkeiser** [comment]
A note since you're running things on various architectures. If you want to separate the effect of the `if` nesting from the interleave/unroll, you can run [the interleave/unroll commit](https://github.com/lemire/simdjson/pull/317/commits/880e892bf2053439009d19b81fbf743ade84634f) (`git checkout reorder~1`) by itself without if statements. The rest is / should be identical to the patches that came before (just cumulative).

**Comment by lemire** [comment]
This is amazing work.

**Pull request merged**
