### PR TITLE
Stage2 refactored to simplify multiple implementations

### PR DESCRIPTION
**Pull request by ioioioio**
Next part of the refactoring to simplify the implementation of multiple versions for different instruction sets (see [PR#197](https://github.com/lemire/simdjson/pull/197)).

### CODE REVIEW

**Comment by lemire** [comment]
I verified that the tests pass and that there is no performance effect.

@ioioioio  Please merge when it is convenient to do so.

**Comment by lemire** [comment]
@ioioioio Not that there are now conflicts to be resolved. :-)

**Comment by ioioioio** [comment]
I'm working on this. Should ok soon.

**Comment by lemire** [comment]
+1

**Pull request merged**
