### PR TITLE
Move architecture-specific headers to src/

### PR DESCRIPTION
**Pull request by jkeiser**
The start (and biggest part) of moving implementation-only headers into src and out of include.

* Move stage1_find_marks_*, stage2_build_tape_common, simdutf8check*, stringparsing* and simd_input* into src/ in this directory structure:
  - `src/generic/` - generic headers that may be included more than once, creating separate functions for each architecture.
  - `src/haswell/`, `src/westmere`/, `src/arm64/` - architecture-specific implementations of everything.
* Reduces stage1_find_marks public interface to just `find_structural_bits()`
* Uses namespaces `simdjson::arm64`, `simdjson::haswell` and `simdjson::westmere` to eliminate the need for #defines before including generic header files and use namespace locality instead of templating to call other methods from the same architecture.

### CODE REVIEW

**Comment by jkeiser** [comment]
Hmm. clang seems to want a semicolon that gcc doesn't. Marking [WIP]; I'll investigate further later.

**Comment by lemire** [comment]
Failing tests aside, this is a good idea.

**Comment by jkeiser** [comment]
so nice having a linux on my windows!

**Comment by jkeiser** [comment]
I tweaked things a little more with this patch, making subdirectories for each architecture: src/arm64, src/haswell, src/westmere and src/generic. (I used generic instead of common because what we're doing is closer to templates/generics than to reusing common functions.)

**Comment by jkeiser** [comment]
I'm not sure how to disable the missing header guard warning (it's intentional, part of the new way of include `generic` headers without needing any defines).

**Comment by jkeiser** [comment]
@lemire this one is compiling. There is a pileon change to change stage2 and stringparsing to use the new architecture-include method, but I can make a followon when that's done.

**Comment by jkeiser** [comment]
(Strike that, I made the above changes and am checking it against CI now.)

**Comment by jkeiser** [comment]
All right @lemire, now the defines are gone and the world is green. Done with this patch.

**Comment by jkeiser** [comment]
Ah, removing [WIP] as well.

**Comment by jkeiser** [comment]
Note on LGTM: the new goto is actually an old one that moved; the missing header guards are 100% intentional (these are the generic/*.h files).

**Comment by lemire** [comment]
I am unconcerned by this warning from LGTM.

**Comment by lemire** [comment]
I am concerned with a small (2% to 6%) but measurable performance degradation in stage 1. It seems to affect all architectures.

Let us focus on instruction counts in stage 1 to keep things simple. (Stage 2 is unaffected.) Let us focus on one file (gsoc-2018.json)...

ARM:
before: 8345165 instructions
after: 8848467 instructions
+6%

Haswell+:
before: 6357962 instructions
after: 6498786 instructions
+2%

**Comment by lemire** [comment]
@jkeiser I have disassembled the stage 1 (simdjson::find_structural_bits) and the assembly is almost entirely different. So I think we are not compiling the exact same code?

**Comment by lemire** [comment]
Let us look at the instruction counts that differ... in ARM...

old code has 5 b and 3 b.hi, 6 b.le instructions... (total 10)
new code has 8 b, 2 b.gt, 2 b.hi, 4 b.le, 1 b.ls instructions... (total 17)

old code has 4 cbnz...
new code has 5 cbnz...

old code had 41 movi
new code has 27 movi

So the new code has fewer moves, but many more branches.

**Comment by lemire** [comment]
When I look at the metrics... I see that the new code has many more cache accesses (875569 vs 653460).

Note that this is just during stage 1.... stage 2 is identical. This is under ARM.

**Comment by lemire** [comment]
The extra cache accesses does not pan out under x64.

**Comment by lemire** [comment]
Amusingly my changes fail the sse perf test!!!

**Comment by lemire** [comment]
Rerunning.

**Comment by lemire** [comment]
@jkeiser According to folks on Twitter (Krister Walfridsson and Travis Downs), the difference in performance due to the 'static' keyword may be due to when the compiler does the inlining (early vs late).

**Comment by jkeiser** [comment]
The changes look good. Nice sleuthing. 

I'm super surprised the `static` made a difference, but I can't think why I added them either--a lesson about making "innocuous" changes. I'm curious why the TARGET_HASWELL wasn't needed on those namespaces? We had them in the original files.

I'm good with your changes, and if you're good with mine, merging is our next step.

**Comment by lemire** [comment]
1. The unneeded targets are not part of your PR, but clang did not like them. The target only applies to functions and when there is no functions within the range, the compiler can issue a warning. Initially, I think that our spirit was to spread the architecture targets generously, to make sure that the compiler wasn't shy... but in this instance, it is clearly unneeded, I think.

2. Of course, the 'static' qualifiers should not be expected to make a difference... but empirically, they do. And because they are unneeded in the first place, even if we did not care about the performance effect (which is probably compiler specific), it is probably good to take them out.

I'll merge.

**Comment by lemire** [comment]
Merged.

**Comment by jkeiser** [comment]
Ah, this is because I broke up the namespace a little and put targets on files without any functions in them. Got it!

**Pull request merged**
