### PR TITLE
STRINGIFY implemented

### PR DESCRIPTION
**Pull request by DBJDBJ**
STRINGIFY implemented

### CODE REVIEW

**Comment by DBJDBJ** [comment]
SIMDJSON_THREADS_ENABLED is now def/undef. It was hash defined to 1

This now aligns with usage elsewhere. 

As an example see `int JsonStream::json_parse(ParsedJson &pj);` implementations. Before these change  SIMDJSON_THREADS_ENABLED code was always compiled in.

**Comment by DBJDBJ** [comment]
Now that I have `SIMDJSON_THREADS_ENABLED` actually undef'd, the #else code in `int JsonStream::json_parse(ParsedJson &pj);`  implementation, kicks-the-bucket  or flips-the-tables

image

on line 2337 -- this is my amended single header simdjson.cpp

**Comment by lemire** [comment]
I will merge this. If there is an issue, please report it as an actual issue, so we can track it. Please don't report potential bugs as mere comments... if you think that it is a bug, please make a genuine issue out of it.

**Comment by DBJDBJ** [comment]
... have opened two projects here on two monitors .. compiled/debug is happening on the single header repo I made from SJ single header folder ... that is very fast and comfortable using VS Code, but then going back to SJ fork on the second monitor to match the findings ... 

As you know jsonstream was "funny" let me do that one and open the pull request ...

**Pull request merged**
