### PR TITLE
Streams of JSON documents + Large files (>4GB) (#350)

### PR DESCRIPTION
**Pull request by piotte13**
Hello everyone, 
We got a working prototype that could solve this issue and allow us to support large files (>4GB)! 

### Exemple usage:

```cpp
#include "simdjson/parsedjson.h"
#include "simdjson/jsonstream.h"

simdjson::padded_string string;
simdjson::get_corpus(filename).swap(string);


//simdjson::JsonStream js{string};
//simdjson::JsonStream js{string, 1000000};
//simdjson::JsonStream js{string.data(), string.size()};
simdjson::JsonStream js{string.data(), string.size(), 1000000}; 
//Where 1000000 represents the batch_size in bytes.  
//We load data in batch to speed things up a bit. (default = 1MB)


int parse_res = simdjson::SUCCESS_AND_HAS_MORE;
simdjson::ParsedJson pj;

//We re-use the same ParsedJson as much as possible, to save allocation time.
//This loop will run as long as the file contains valid JSON documents.
while (parse_res == simdjson::SUCCESS_AND_HAS_MORE) {
    parse_res = js.json_parse(pj);
}
```
### Implementation
The current implementation allows us to parse through large documents faster than the "simple" `std::getline()` alternative.  We still have many ideas to make it even faster, but right now it feels like a good starting point.

### What kind of file is supported?
We opted for a more general case where a file could contain multiple JSON documents no matter the format, as long as it is JSON valid. Therefore, we are not limited to ndjson and jsonline. **We support any file that contains multiple valid JSON documents.**

### API
**I would greatly appreciate some feedback.**  From my point of view, it seems simple and easy to use, but i'm not an end user! 

- Does it fill your needs?
- Is it clear, simple and complete enough?
- Suggestions?

Cheers

### CODE REVIEW

**Comment by lemire** [comment]
The failing test refers to a minor perf. regression under ARM which as far as I know is not relevant with respect to this PR.

I think we can merge this PR as soon as the author recommends it.

**Comment by piotte13** [comment]
I will merge this for now and I will make another pull request concerning the documentation.

**Comment by rbnx** [comment]
@piotte13  I tested this new functionality after it got merged and it only seems to work with line-delimited JSON files, is there a plan to add support for 4gb+ files that are not line-delimeted.

**Comment by lemire** [comment]
@rbnx It would be best to open a new issue so we can track the problem.

I think that the intention is definitively to provide broad support and not require line-delimitation.

cc @piotte13

**Pull request merged**
