### PR TITLE
Resolves issue 186

### PR DESCRIPTION
**Pull request by lemire**
https://github.com/lemire/simdjson/issues/186

### CODE REVIEW

**Comment by lemire** [comment]
This PR removes 35,000 lines of code with basically no downside. Can anyone beat this?

cc @jkeiser  @piotte13

**Comment by lemire** [comment]
Fails to compile in some conditions...

**Comment by piotte13** [comment]
+1

**Comment by lemire** [comment]
Ok. It was a case of a missing "}".

**Comment by jkeiser** [comment]
Super happy about the smaller include file and thus public surface :)

**Comment by lemire** [comment]
@jkeiser This has been on my todo list for nearly 6 months. I am really glad it is done.

**Pull request merged**
