### PR TITLE
clarifications -- documentation update

### PR DESCRIPTION
**Pull request by DBJDBJ**
No need to merge for now ...  I am here due to a general mild confusion due to the lack of architectural/design documentation. Hopefully, the outcome of discussion here will be better documentation, and perhaps even better implementation.

### Exhibit A : simdjson streams
Let the code speak. Questions are in the comments.

```cpp
#include "simdjson.h"
#include "simdjson.cpp"

int parse_file(const char *filename) {
    // padded_string copies the json string taken from a file
   // into the memory, true ?
   //  after this line p contains potentially  very large amount of heap alocated storage, right?
    simdjson::padded_string p = simdjson::get_corpus(filename);

   // 'ParsedJson' seems to be what the 'Tape' is?
   // it is a final product of json parsing, also staying in the memory
   // thus it will contain a very large amount of heap allocated storage, true?
   // thus size of the heap taken in this function will be minimum twice the 
   // size of the file read in. True?
    simdjson::ParsedJson pj;
    simdjson::JsonStream js{p};
    int parse_res = simdjson::SUCCESS_AND_HAS_MORE;
    
    while (parse_res == simdjson::SUCCESS_AND_HAS_MORE) 
        {
           // I fail to see how is 'JsonStream' helping here
          // it seems stream vs tape interaction can be 
          // encapsulted into the 'ParsedJson'
            parse_res = js.json_parse(pj);

            //Do something with pj...
        }
}
```
Talking about API, in general, I fail to see what might be wrong with the following refactoring of the above :
(beside the fact huge amounts might be allocated on the heap, leading to excessive paging) 
```cpp
#include "simdjson.h"
#include "simdjson.cpp"

int parse_file(const char *filename) {

   // refactored into standard container
    simdjson::ParsedJson parsed_json_( filename );
    // thus one can do standard C++ range 
    // for example
     for ( auto & dom_iterator_ :  parsed_json_ )
    {
        // dom_iterator_  type is  simdjson::ParsedJson::Iterator 
        // refactored into standard C++ bidirectional iterator
    }
    // thus one can use
    // std alorigthms, for example
   auto  first_image = std::find(  parsed_json_.begin(),  parsed_json_.end() ,
          [](  string const & key, auto & value ) { 
                       if ( key == "Image" ) return true; else return false;   
           }
    );
}
```

### CODE REVIEW

**Comment by lemire** [comment]
Json stream is for parsing streams of JSON documents. Please see
https://github.com/lemire/simdjson/blob/master/doc/JsonStream.md

It would certainly be possible and desirable to offer the standard C++ interface on top of it.

**Comment by jkeiser** [comment]
I like the iterator interface.

> ```c++
>    // 'ParsedJson' seems to be what the 'Tape' is?
> ```

[ParsedJson](https://github.com/lemire/simdjson/blob/master/include/simdjson/parsedjson.h#L122-L134) contains both the output DOM (tape, containing_scope_offset and string_buf), and buffers used internally during parsing (structural_indexes and ret_address) which aren't really useful to the DOM.

I'd like to see the internal state separated out into a `JsonParser` object, but that's a side conversation.

> ```c++
   // it is a final product of json parsing, also staying in the memory
   // thus it will contain a very large amount of heap allocated storage, true?
> ```

Definitely.

> ```c++
   // thus size of the heap taken in this function will be minimum twice the 
   // size of the file read in. True?
> ```

Adding it up in my head, it's [on the order of **fourteen times the file size.**](https://github.com/lemire/simdjson/blob/master/src/parsedjson.cpp#L24-L35) to take the worst case into account (u64 per byte for the tape, u32 and null terminator every 3 bytes for string tape, u32 per byte for structural indexes).

I'd *love* there to be an incremental parser, but JsonStream isn't that (it seems to be for people who want to paste a bunch of valid json documents together; the JSON parser will return after parsing each one). The desire to keep memory footprint down (and cache high) with incremental parsing is ongoing [here](https://github.com/lemire/simdjson/issues/439) and [here](https://github.com/lemire/simdjson/issues/442) and some progress was made [here](https://github.com/lemire/simdjson/pull/406). I don't believe that discussion is focused on producing incremental *output*, but it's likely a hop skip and jump away once you have piecemeal parsing.

> Talking about API, in general, I fail to see what might be wrong with the following refactoring of the above :

I like the simplicity of the interface.

One small bikeshed: I think I'd want to see the verb `parse` or `parse_file` in there somewhere rather than parsing in the constructor of `ParsedJson`. Like, `JsonParser parser(); ParsedJson json = parser.parse_file(filename);` or even `ParsedJson json = parse_json_file(filename);` I know that wasn't at all the main point of your post, though :)

**Comment by lemire** [comment]
> I'd like to see the internal state separated out into a JsonParser object, but that's a side conversation.


I agree. I expect that it is one of our open issues.

> Adding it up in my head, it's on the order of fourteen times the file size.

This is *virtual* memory allocation. It is not a concern per se.

Try it out. Do "int * buffer = new int[somebignumber]". This line will be almost free... return immediately... and even if "somebignumber" is large, you will likely not see any impact on your system.

We want to take the memory usage down,  but that's to avoid page allocations (so physical memory allocation).

It is fine to reserve massive amounts of virtual memory.

>  I don't believe that discussion is focused on producing incremental output, but it's likely a hop skip and jump away once you have piecemeal parsing.

If you have large documents (say 50 MB and up) and you cannot reuse the same pre-allocated memory pages, then partial/incremental/iterative/custom outputs are a necessity.

**Comment by DBJDBJ** [comment]
> Json stream is for parsing streams of JSON documents. Please see
> https://github.com/lemire/simdjson/blob/master/doc/JsonStream.md

@lemire I was through that doc and through the code as you know. What I see in the example in that doc is a function receiving a single file name. simdjson stream (I assume) can handle one or more JSON documents. I the code I see no handle to the "stream" of values, like for example `std::istream` is.

I assume a code using several json files simply adds together strings obtained by slurping the each file into one string?

```cpp
int main() {
    using namespace std;
   // 30.5 MB
    ifstream ifs_1("amazon_cell_phones.json");
    string str_1(istreambuf_iterator<char>{ifs_1}, {});
  // 3.2 MB
    ifstream ifs_2("kepler.json");
    string str_2(istreambuf_iterator<char>{ifs_2}, {});
 // 2.7 GB
    ifstream ifs_3("dbsnp.json");
    string str_3(istreambuf_iterator<char>{ifs_3}, {});

  using namespace simdjson ;

   padded_string ps_(   str_1 + str_2 + str_3  ) ;

    simdjson::ParsedJson pj{};
    simdjson::JsonStream js{ps_};
    int parse_res = simdjson::SUCCESS_AND_HAS_MORE;
     while (parse_res == simdjson::SUCCESS_AND_HAS_MORE) 
        {
            parse_res = js.json_parse(pj);
            //Do something with pj...
        }
}
```
This is how I assume you imagine  "streaming several files"?  It seems we just have the terminology issue.

I specified once an (HP DL 360) server with 240 GB RAM, 9 x 900GB SAS disks and 4 Xeon CPUs, 4 cores each.  I think that machine just might be able to run the program above with the json files as above. 

Parsing in junks is a good strategy. There are two problems though: what is a chunk in the context of JSON, and how do you tell the JSON has no right brace at the end. if the end is a few gigabytes far?

**Comment by lemire** [comment]
In JSON stream, we support the json line and ndjson specifications which are the standards for stream JSON documents.

**Comment by DBJDBJ** [comment]
Ah ok,  when you say "stream" you mean in the NDJSON context, ok. 

On the server-side, there are no JSON files. JSON is always coming in as https payload or web sockets payload.  NDJSON is invented for that situation. 

Thus, I assume one might make simdjson front, which receives NDJSON "lines" "over a wire" and sends them to the simdjson.  I assume further each NDJSON "line" will come out as one simdjson Tape instance. 

What, I am getting at: this is all good since sending huge chunks of unbroken JSON over a wire is not that "automagical" as it might look. So, on the server-side, it is a very unlikely JSON file or large JSON files will ever appear.

**Comment by DBJDBJ** [comment]
@jkeiser 
> One small bikeshed: I think I'd want to see the verb parse or parse_file in there somewhere rather than parsing in the constructor of ParsedJson. Like, JsonParser parser(); ParsedJson json = parser.parse_file(filename); or even ParsedJson json = parse_json_file(filename); I know that wasn't at all the main point of your post, though :)

No worries ... "POD like" (no constructors) structs + factory friend functions.  I would be really happy with:
```cpp
simdjson::Tape tape_ = simdjson::parse ( input_in_a_string_  ) ;
```

**Comment by lemire** [comment]
Regarding ndjson, here is what the first few lines of the documentation state:

> NDJSON is a convenient format for storing or streaming structured data that may be processed one record at a time. It works well with unix-style text processing tools and shell pipelines. It's a great format for log files. It's also a flexible format for passing messages between cooperating processes.

Ref: http://ndjson.org

So the expectation is indeed that you have one large file (e.g., a log file).

HTTP server-client is something else... I think that @jkeiser created an issue for this other context.

**Comment by DBJDBJ** [comment]
> Regarding ndjson, here is what the first few lines of the documentation state:
> 
> > NDJSON is a convenient format for storing or streaming structured data that may be processed one record at a time. It works well with unix-style text processing tools and shell pipelines. It's a great format for log files. It's also a flexible format for passing messages between cooperating processes.
> 
> Ref: http://ndjson.org
> 
> So the expectation is indeed that you have one large file (e.g., a log file).
> 
> HTTP server-client is something else... I think that @jkeiser created an issue for this other context.

@lemire , I am confused what are you arguing if you are arguing :) 

If NDJSON spec says NDJSON is "great format for log files" that does not mean people are using NDJSON for log files.  

I have never seen, in production, software being accepted, that is making any kind of log files instead of sending syslog messages.

**Comment by lemire** [comment]
This PR looks good, merging. 

Discussion regarding the API should probably be carried over elsewhere.

**Pull request merged**
