### PR TITLE
std::tie does not work on some compilers

### PR DESCRIPTION
**Pull request by lemire**
This is a workaround.

### CODE REVIEW

**Comment by lemire** [comment]
This is a big ugly, but it is kind of bad to not be able to compile on a mac. And I think that the net result is good.

**Comment by lemire** [comment]
I verified that it does not carry a performance cost. I am going to merge this to ease development. It can be easily reversed later once we figure it out.

I am tired of fighting the compiler.

**Comment by jkeiser** [comment]
@lemire I don't have a Mac here to check, but just to let you know, the fundamental operation that needs to work for `tie` to work is `pair<A&,B&> = pair<A,B>`. That was actually why I moved everything to `simdjson_result`, so that I could inherit that from `std::pair`--that's the magic that makes it work.

 Is it possible we could fix Mac by creating that overloaded operator directly? i.e.

``c++
template<typename T>
bool operator=(std::pair<T&,error_code&> out, simdjson_result<T>& in) { out.first = r.first; out.second = r.second; }
```

**Comment by lemire** [comment]
The operator= takes only one parameter and therefore must be inside the std::pair class definition...

**Comment by lemire** [comment]
Here is the complete error:
```

tests/basictests.cpp:896:26: error: no viable overloaded '='
    std::tie(val, error) = doc["d"];//.tie(val, error);
    ~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/tuple:872:12: note: 
      candidate function not viable: no known conversion from 'document::element_result' to 'const typename
      conditional<_CanCopyAssign::value, tuple<element &, error_code &>, __nat>::type' (aka 'const
      std::__1::tuple<simdjson::document::element &, simdjson::error_code &>') for 1st argument
    tuple& operator=(typename conditional<_CanCopyAssign::value, tuple, __nat>::type const& __t)
           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/tuple:880:12: note: 
      candidate function not viable: no known conversion from 'document::element_result' to 'typename
      conditional<_CanMoveAssign::value, tuple<element &, error_code &>, __nat>::type' (aka
      'std::__1::tuple<simdjson::document::element &, simdjson::error_code &>') for 1st argument
    tuple& operator=(typename conditional<_CanMoveAssign::value, tuple, __nat>::type&& __t)
           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/tuple:895:9: note: 
      candidate template ignored: requirement '__tuple_assignable<simdjson::document::element_result,
      std::__1::tuple<simdjson::document::element &, simdjson::error_code &>, false, true>::value' was not
      satisfied [with _Tuple = simdjson::document::element_result]
        operator=(_Tuple&& __t) _NOEXCEPT_((is_nothrow_assignable<_BaseT&, _Tuple>::value))
```

**Comment by lemire** [comment]
Note that the following works fine...

```
#include <tuple>

std::pair<int,int> give(int x1, int x2) {
  return std::pair<int,int>(x1,x2);
}

int main() {
  int x = 0;
  int y = 0;
  std::tie(x,y) = give(1,2);
}
```

**Comment by lemire** [comment]
The following works fine

```
#include <iostream>
#include <string>
#include <set>
#include <tuple>
 
struct S {
    int n;
    std::string s;
    float d;
    bool operator<(const S& rhs) const
    {
        // compares n to rhs.n,
        // then s to rhs.s,
        // then d to rhs.d
        return std::tie(n, s, d) < std::tie(rhs.n, rhs.s, rhs.d);
    }
};
 
int main()
{
    std::set<S> set_of_s; // S is LessThanComparable
 
    S value{42, "Test", 3.14};
    std::set<S>::iterator iter;
    bool inserted;
 
    // unpacks the return value of insert into iter and inserted
    std::tie(iter, inserted) = set_of_s.insert(value);
 
    if (inserted)
        std::cout << "Value was inserted successfully\n";
}

```

**Comment by lemire** [comment]
The following also work...

```
// packing/unpacking tuples
#include <iostream>     // std::cout
#include <tuple>        // std::tuple, std::make_tuple, std::tie

int main ()
{
  int myint;
  char mychar;

  std::tuple<int,float,char> mytuple;

  mytuple = std::make_tuple (10, 2.6, 'a');          // packing values into tuple

  std::tie (myint, std::ignore, mychar) = mytuple;   // unpacking tuple into variables

  std::cout << "myint contains: " << myint << '\n';
  std::cout << "mychar contains: " << mychar << '\n';

  return 0;
}
```

**Comment by lemire** [comment]
@jkeiser  I think I figured it out. You can use `std::tie` if the RHS is either a tuple or a pair. Derived classes are not allowed.

**Comment by lemire** [comment]
This fails. I will open an issue to track this.
```
#include <tuple>
struct t : std::tuple<int,float,char> {};
int main () {
int myint; char mychar;
t tt;
std::tie (myint, std::ignore, mychar) = tt;
}
```

**Pull request merged**
