### PR TITLE
With this commit we can do all tests with full sanitizers on, and get no warning

### PR DESCRIPTION
**Pull request by lemire**
Running this with 

```
make clean
make SANITIZEGOLD=1 test
```

I get a clean bill of health. 

Try also...

```
make clean
make SANITIZEGOLD=1  parse
for i in jsonexamples/*.json; do echo $i; ./parse $i; done
```

Again, nothing here. Tested with GCC 8. (Results may differ if you use a different compiler.)

By full sanitizers, I mean `-fsanitize=address -fno-omit-frame-pointer -fsanitize=undefined`, so memory checks and undefined behaviour.

### CODE REVIEW

**Comment by lemire** [comment]
@geofflangdale I'm letting you merge this since you are presumably doing some work at the same time.

**Comment by EmilGedda** [comment]
https://github.com/lemire/simdjson/blob/a31de6c8c03e5d18b5acddb4a48659e7a7da75d9/Makefile#L16-L18

Wouldn't it be better to separate this into a its own branch, instead of duplicating the sanitizing flags?
I'm thinking something like this:

```make
ifdef LINKER
	CXXFLAGS += -fuse-ld=$(LINKER)
	CFLAGS += -fuse-ld=$(LINKER)
endif
```
And then the user simply does `make LINKER=gold allparsercheckfile`.

**Comment by lemire** [comment]
@EmilGedda 

What about *adding* the `LINKER=gold` flag as well as the `SANITIZEGOLD=1` (as a convenience shorthand)?

**Comment by EmilGedda** [comment]
> What about _adding_ the `LINKER=gold` flag as well as the `SANITIZEGOLD=1` (as a convenience shorthand)?

That would work too, I would implement that as follows placing it just before the other conditionals:
```make
ifdef SANITIZEGOLD
    SANITIZE = 1
    LINKER = gold
endif
```


If you don't want to repeat flags while repeatedly calling make during your development cycle, you can simply `export  SANITIZE=1 LINKER=gold` and all subsequent calls to `make` in that shell will build with sanitizer and gold, same goes for C(XX)FLAGS of course.

**Comment by lemire** [comment]
@EmilGedda That sounds good. I committed just that.

**Comment by lemire** [comment]
@geofflangdale  This is done. We have safer code.

**Pull request merged**
