### PR TITLE
simdjson.h and portability.h

### PR DESCRIPTION
**Pull request by DBJDBJ**
Basically and hopefully cleaned things a bit in simdjson.h
Added compile-time str len and str compare in nanolib namespace in there
few more compile time functions.

added fast fail policy in portability.h to conditionally exit (as default) on aligned malloc failure.

### CODE REVIEW

**Comment by DBJDBJ** [comment]
`simdjson::architecture_services` should speed things up and make the overall code more resilient ... and a bit shorter

**Comment by DBJDBJ** [comment]
Ok we have now "isadetection.h" not found from amalgamation  demo...

Is it something I have done?

**Comment by lemire** [comment]
@DBJDBJ Can you break down this PR into small PRs? There is too much here to review that is semantically distinct.

**Comment by DBJDBJ** [comment]
I would gladly do that.  But. How does one break one overgrown PR into smaller PR's?

I have been wondering why is every little commit I do on my fork, automagically attached/shown on this one PR? Let me close this one and try again.

**Comment by DBJDBJ** [comment]
I would gladly do that.  But. I made a cardinal mistake of not splitting into branches on my side.
Thus every little commit I do on my fork, is automagically attached/shown on this one PR? Let me close this one and try some git jamboree.

**Pull request closed without merging**
