### PR TITLE
Change parse_json return type from bool to int

### PR DESCRIPTION
**Pull request by atomheartother**
This branch is my attempt to make `parse_json` behave as is standard for C functions, i.e. have it return 0 on success and an error code otherwise. 

# Major Changes
## simdjerr namespace
There's now a new header, located at `simdjson/simdjerr.h`. This header defines the `simdjerr` namespace (really a struct which only has a static method), which contains an enum for return values. This enum is **weakly typed** (C-style), because making users `static_cast` to int seems like too much of a pain for the potential benefits.

Ideally we should gradually transition public-facing function returns to this enum, so that the user can get a meaningful message out of it later, rather than us printing to console.

The namespace also defines the method `errorMsg()` which takes an error code as parameter and returns a meaningful error message. The readme includes an usage example.

## Removed parse_json logs on error, returned int instead 
`parse_json`, along with the functions it calls and checks the return value off, now don't print their error messages to `stderr`, they return a value scoped within `simdjerr` on error, and 0 on success.

**This breaks backwards-compatibility** as the old return value on success was 1. The README example has been updated accordingly.

# Small changes
- `json2json`, `parse` and `jsoncheck` have been  updated to match the new return values.
- Move two static inline functions for `unified_machine` and `find_structural_bits` from header files to their respective `.cpp` files. I don't see any reason to have these functions as inline static, they will cause warnings if they're included & unused and will inflate binary size unnecessarily.

# To do
- Triple-check that every tool and benchmarking tool shipped with this repo conforms to the new return values, I might not know them all.
- Transition more functions to the `simdjerr` namespace
- ~~Add a static function to the `simdjerr` namespace which returns a string when given an error code, in order to allow for meaningful debugging for the user.~~
- ~~Update the single-header version~~

### CODE REVIEW

**Comment by atomheartother** [comment]
@TkTech to answer your feedback on #81 (broken version of this PR):

> Is there a reason these are in their own namespace? They should probably be in the same namespace as simdjson (...which also needs to be namespaced).

Well, like you said, simdjson isn't namespaced. If there's a central `simdjson` namespace we could move this enum there yes.

> Define error strings for each error code rather than a comment, so the rest of the code and people using simdjson as a library can get the error strings.
I don't think we need to expose these strings there (which, every string we write a string in a header its size is multiplied by how many files it's included in), we can just have a function that returns a static string when given an error code, which is what I suggested we do in my todo list. Either way the comments most definitely aren't meant to be how users access the message no :p

**Comment by atomheartother** [comment]
I see the tests passed even before i updated the single-header version. We should probably include the single-header version to CI if we're going to seriously maintain & keep it up to date

**Comment by lemire** [comment]
@atomheartother 

This is maybe not best... but my expectation is that the single-header code will not change frequently. It is basically a release artefact.

The intention is that single-header are updated *on release*, and as part of their creation there is a small sanity test. 

They don't currently undergo much testing, only that it compiles and can parse a single JSON file. However, it is just an aggregate with *no code change* so the probably that new bugs emerge just in the single-header code is... low.

**Comment by atomheartother** [comment]
@lemire That's fair, I've updated it here since my change basically invalidates the basic readme example so I felt it was worth updating the single-header, but i can see why we would only update single-header every so often.

In other news I now feel comfortable with this branch being merged, it can still be improved but that can be done in later iterations

**Comment by lemire** [comment]
At a glance, this looks great... I'll wait for other people to get a chance to look at it.

cc @geofflangdale

**Comment by geofflangdale** [comment]
I like this. 

We were a bit casual about namespacing; I would prefer a single simdjson namespace rather than the fairly awkward simdjerr namespace (with a public API namespace to follow?). We should be more careful about namespaces in general; I suspect a lot of stuff should be in anon namespaces (does this play well with single-header versions - I don't know!).

**Comment by atomheartother** [comment]
I agree with changing the namespace to `simdjson`.

**Comment by atomheartother** [comment]
That's done. I've renamed the files `simdjson.cpp` and `simdjson.h`. I get that these names might get confusing with the single-header file names but, well, it just seems like an appropriate name, and since the single header version is a separate project the file names do not and never should conflict.

**Comment by atomheartother** [comment]
Also it appears one of my tests fails on windows from appveyor, I don't have a windows machine on hand so if someone can shed light on why that is I'll try and fix it.

**Comment by lemire** [comment]
I think it is just timing out, not failing per say. This may need to be investigated separately.

I am not sure why it would time out, but I doubt you have anything to do with it.

**Comment by lemire** [comment]
Optimistically restarting appveyor.

**Comment by lemire** [comment]
@atomheartother I have issued a PR against your PR since I think the amalgamation script needs to be updated. 

Moreover I am secretly hoping this might make appveyor happy for unknown reasons.

**Comment by lemire** [comment]
This PR does not appear to negatively affect the speed...

```
$ git checkout master && make parse && ./parse jsonexamples/twitter.json  && git checkout parseJsonInt && make parse && ./parse jsonexamples/twitter.json
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
g++-8 -std=c++17  -march=native -Wall -Wextra -Wshadow -Iinclude  -Ibenchmark/linux -O3 -o parse src/jsonioutil.cpp src/jsonparser.cpp src/stage1_find_marks.cpp         src/stage2_build_tape.cpp src/parsedjson.cpp src/parsedjsoniterator.cpp benchmark/parse.cpp
number of bytes 631514 number of structural chars 55264 ratio 0.088
mem alloc instructions:       1210 cycles:        848 (0.07 %) ins/cycles: 1.43 mis. branches:          5 (cycles/mis.branch 149.07) cache accesses:      28008 (failure          0)
 mem alloc runs at 0.00 cycles per input byte.
stage 1 instructions:    1934733 cycles:     634205 (54.35 %) ins/cycles: 3.05 mis. branches:       1435 (cycles/mis.branch 441.86) cache accesses:      28008 (failure          1)
 stage 1 runs at 1.00 cycles per input byte.
stage 2 instructions:    1530272 cycles:     531858 (45.58 %) ins/cycles: 2.88 mis. branches:       1598  (cycles/mis.branch 332.66)  cache accesses:      48966 (failure          1)
 stage 2 runs at 0.84 cycles per input byte and 9.62 cycles per structural character.
 all stages: 1.85 cycles per input byte.
Min:  0.000356856 bytes read: 631514 Gigabytes/second: 1.76966
Switched to branch 'parseJsonInt'
Your branch is up-to-date with 'origin/parseJsonInt'.
g++-8 -std=c++17  -march=native -Wall -Wextra -Wshadow -Iinclude  -Ibenchmark/linux -O3 -o parse src/jsonioutil.cpp src/jsonparser.cpp src/simdjson.cpp src/stage1_find_marks.cpp        src/stage2_build_tape.cpp src/parsedjson.cpp src/parsedjsoniterator.cpp benchmark/parse.cpp
number of bytes 631514 number of structural chars 55264 ratio 0.088
mem alloc instructions:       1210 cycles:        696 (0.06 %) ins/cycles: 1.74 mis. branches:          1 (cycles/mis.branch 363.57) cache accesses:      28077 (failure          0)
 mem alloc runs at 0.00 cycles per input byte.
stage 1 instructions:    1934734 cycles:     633333 (54.33 %) ins/cycles: 3.05 mis. branches:       1415 (cycles/mis.branch 447.40) cache accesses:      28077 (failure          1)
 stage 1 runs at 1.00 cycles per input byte.
stage 2 instructions:    1544318 cycles:     531792 (45.62 %) ins/cycles: 2.90 mis. branches:       1575  (cycles/mis.branch 337.62)  cache accesses:      49053 (failure          0)
 stage 2 runs at 0.84 cycles per input byte and 9.62 cycles per structural character.
 all stages: 1.85 cycles per input byte.
Min:  0.00035645 bytes read: 631514 Gigabytes/second: 1.77168
```

**Comment by lemire** [comment]
Status: Waiting for @atomheartother to review my PR on his own PR. :-)

**Comment by atomheartother** [comment]
@lemire my apologies for being so slow - it's now merged c:

**Comment by lemire** [comment]
> my apologies for being so slow

Get better coffee. (Joke.)

It is freaking Saturday. I wasn't expecting an answer.

**Comment by lemire** [comment]
This has support from @geofflangdale, and I checked that it did not obviously harm performance. So merging...

**Pull request merged**
