### PR TITLE
Break structural scanner from stage1

### PR DESCRIPTION
**Pull request by jkeiser**
For a number of specific use cases (such as minification), it would be nice to have the ability to run the stage 1 scanner without writing indexes into a tape. This patch abstracts the `json_scanner` from the `json_structural_indexer` in this checkin, in hopes I can use it elsewhere. I also split out `json_string_scanner` since it can travel pretty effectively as a unit; though that was less necessary.

I probably wouldn't check it in since it's just a refactor, but it turns out it's faster on my machine: stage 1 rises by about 3%, so overall we probably win a little over 1%.

### CODE REVIEW

**Comment by jkeiser** [comment]
Note: I can't be sure the cause of the minor performance gain, because I changed a lot. But one likely change was, the `json_block` object emitted by the json_scanner leaves some of the last few calculations (such as `structurals & ~strings` in inline functions instead of putting them in variables. The optimizer may have felt like it had more leeway when optimizing these, leading to better register usage or more optimal instruction ordering.

**Comment by jkeiser** [comment]
One of the experiments I'd like to use this for is compiling stage 1 and stage 2 together for a fully streaming processor :) I'm expecting it to take longer than it currently does, actually, because stage 2's branchiness is likely to murder stage 1's superscalar chewy goodness.

**Comment by jkeiser** [comment]
I can't get on to Skylake, but the results from latest master show on the order of 2% stage 1 improvement on Haswell (Kady Lake R actually) and no change on Ampere ARM:

| Architecture | Patch | Master |
|---|---|---|
| Ampere      | 0.719 GB/s | 0.719 GB/s |
| Kady Lake R | 5.924 GB/s | 5.810 GB/s |

**Comment by lemire** [comment]
@jkeiser Skylake is down. I have an AMD Rome that is still up (you have access?).

I am trying to get the servers back up but you may have heard something about a virus and universities closing?

**Comment by lemire** [comment]
Ok. On AMD Rome, the number of cycles goes up or down... but it is mostly a wash... (for each file, first number is this PR, second number is master)

```
$ for i in jsonexamples/*.json; do echo $i ; ./parse $i |grep Cycles | head -n 1; ./parsemaster $i |grep Cycles | head -n 1; done
jsonexamples/apache_builds.json
|    Cycles       :  99.0850 per block    ( 99.28%) -   1.5485 per byte    -  15.9398 per structural    -    3.373 GHz est. frequency
|    Cycles       :  98.8034 per block    ( 99.16%) -   1.5441 per byte    -  15.8945 per structural    -    3.374 GHz est. frequency
jsonexamples/canada.json
|    Cycles       : 254.1515 per block    ( 99.82%) -   3.9712 per byte    -  26.7344 per structural    -    3.389 GHz est. frequency
|    Cycles       : 253.7092 per block    ( 99.86%) -   3.9642 per byte    -  26.6879 per structural    -    3.389 GHz est. frequency
jsonexamples/citm_catalog.json
|    Cycles       :  86.5602 per block    ( 99.69%) -   1.3525 per byte    -  17.1784 per structural    -    3.391 GHz est. frequency
|    Cycles       :  86.8405 per block    ( 99.81%) -   1.3569 per byte    -  17.2340 per structural    -    3.391 GHz est. frequency
jsonexamples/github_events.json
|    Cycles       :  93.1994 per block    ( 99.05%) -   1.4567 per byte    -  20.3774 per structural    -    3.353 GHz est. frequency
|    Cycles       :  93.3360 per block    ( 98.90%) -   1.4588 per byte    -  20.4072 per structural    -    3.355 GHz est. frequency
jsonexamples/gsoc-2018.json
|    Cycles       :  67.7197 per block    ( 99.64%) -   1.0581 per byte    -  46.4299 per structural    -    3.387 GHz est. frequency
|    Cycles       :  68.8192 per block    ( 99.76%) -   1.0753 per byte    -  47.1837 per structural    -    3.392 GHz est. frequency
jsonexamples/instruments.json
|    Cycles       : 107.5722 per block    ( 99.09%) -   1.6809 per byte    -  13.6301 per structural    -    3.382 GHz est. frequency
|    Cycles       : 107.1490 per block    ( 99.40%) -   1.6742 per byte    -  13.5765 per structural    -    3.382 GHz est. frequency
jsonexamples/marine_ik.json
|    Cycles       : 266.1571 per block    ( 99.61%) -   4.1587 per byte    -  19.2958 per structural    -    3.387 GHz est. frequency
|    Cycles       : 264.5854 per block    ( 99.62%) -   4.1342 per byte    -  19.1819 per structural    -    3.389 GHz est. frequency
jsonexamples/mesh.json
|    Cycles       : 256.8312 per block    ( 97.75%) -   4.0133 per byte    -  18.9464 per structural    -    3.391 GHz est. frequency
|    Cycles       : 256.6579 per block    ( 97.26%) -   4.0106 per byte    -  18.9336 per structural    -    3.392 GHz est. frequency
jsonexamples/mesh.pretty.json
|    Cycles       : 160.7049 per block    ( 98.50%) -   2.5111 per byte    -  25.8419 per structural    -    3.380 GHz est. frequency
|    Cycles       : 161.2567 per block    ( 97.47%) -   2.5197 per byte    -  25.9306 per structural    -    3.388 GHz est. frequency
jsonexamples/numbers.json
|    Cycles       : 214.7417 per block    ( 99.68%) -   3.3558 per byte    -  25.1854 per structural    -    3.386 GHz est. frequency
|    Cycles       : 213.9399 per block    ( 99.06%) -   3.3433 per byte    -  25.0914 per structural    -    3.386 GHz est. frequency
jsonexamples/random.json
|    Cycles       : 151.9275 per block    ( 99.55%) -   2.3741 per byte    -  13.7692 per structural    -    3.390 GHz est. frequency
|    Cycles       : 152.5951 per block    ( 99.33%) -   2.3845 per byte    -  13.8297 per structural    -    3.390 GHz est. frequency
jsonexamples/twitterescaped.json
|    Cycles       : 216.1949 per block    ( 99.67%) -   3.3782 per byte    -  34.3796 per structural    -    3.391 GHz est. frequency
|    Cycles       : 216.1360 per block    ( 99.37%) -   3.3773 per byte    -  34.3702 per structural    -    3.391 GHz est. frequency
jsonexamples/twitter.json
|    Cycles       : 101.8566 per block    ( 99.35%) -   1.5916 per byte    -  18.1880 per structural    -    3.389 GHz est. frequency
|    Cycles       : 101.3166 per block    ( 99.41%) -   1.5832 per byte    -  18.0915 per structural    -    3.389 GHz est. frequency
jsonexamples/update-center.json
|    Cycles       : 124.4963 per block    ( 99.27%) -   1.9453 per byte    -  16.3544 per structural    -    3.389 GHz est. frequency
|    Cycles       : 124.1563 per block    ( 99.26%) -   1.9400 per byte    -  16.3097 per structural    -    3.389 GHz est. frequency
```

The number of instructions, which should remain the same irrespective of the x64 CPU (up to a point) is definitively up... but by such a tiny amount...

```
$ for i in jsonexamples/*.json; do echo $i ; ./parse $i |grep Instructions | head -n 1; ./parsemaster $i |grep Instructions | head -n 1; done
jsonexamples/apache_builds.json
|    Instructions : 312.8301 per block    (100.00%) -   4.8888 per byte    -  50.3251 per structural    -    3.168 per cycle
|    Instructions : 309.8366 per block    (100.00%) -   4.8420 per byte    -  49.8435 per structural    -    3.140 per cycle
jsonexamples/canada.json
|    Instructions : 863.5858 per block    (100.00%) -  13.4937 per byte    -  90.8414 per structural    -    3.396 per cycle
|    Instructions : 860.5860 per block    (100.00%) -  13.4468 per byte    -  90.5258 per structural    -    3.395 per cycle
jsonexamples/citm_catalog.json
|    Instructions : 291.4435 per block    (100.00%) -   4.5539 per byte    -  57.8386 per structural    -    3.360 per cycle
|    Instructions : 288.4390 per block    (100.00%) -   4.5069 per byte    -  57.2424 per structural    -    3.322 per cycle
jsonexamples/github_events.json
|    Instructions : 274.1228 per block    ( 99.99%) -   4.2845 per byte    -  59.9349 per structural    -    2.930 per cycle
|    Instructions : 271.2151 per block    ( 99.99%) -   4.2390 per byte    -  59.2992 per structural    -    2.912 per cycle
jsonexamples/gsoc-2018.json
|    Instructions : 177.9375 per block    (100.00%) -   2.7803 per byte    - 121.9973 per structural    -    2.624 per cycle
|    Instructions : 175.2920 per block    (100.00%) -   2.7390 per byte    - 120.1834 per structural    -    2.549 per cycle
jsonexamples/instruments.json
|    Instructions : 352.3886 per block    (100.00%) -   5.5062 per byte    -  44.6500 per structural    -    3.269 per cycle
|    Instructions : 349.3909 per block    (100.00%) -   5.4594 per byte    -  44.2702 per structural    -    3.253 per cycle
jsonexamples/marine_ik.json
|    Instructions : 779.1071 per block    (100.00%) -  12.1736 per byte    -  56.4836 per structural    -    2.926 per cycle
|    Instructions : 776.0212 per block    (100.00%) -  12.1254 per byte    -  56.2599 per structural    -    2.930 per cycle
jsonexamples/mesh.json
|    Instructions : 830.0587 per block    (100.00%) -  12.9706 per byte    -  61.2333 per structural    -    3.216 per cycle
|    Instructions : 826.9028 per block    (100.00%) -  12.9213 per byte    -  61.0005 per structural    -    3.202 per cycle
jsonexamples/mesh.pretty.json
|    Instructions : 510.2572 per block    (100.00%) -   7.9730 per byte    -  82.0512 per structural    -    3.171 per cycle
|    Instructions : 507.2576 per block    (100.00%) -   7.9262 per byte    -  81.5688 per structural    -    3.159 per cycle
jsonexamples/numbers.json
|    Instructions : 699.4574 per block    (100.00%) -  10.9305 per byte    -  82.0340 per structural    -    3.256 per cycle
|    Instructions : 696.4612 per block    (100.00%) -  10.8837 per byte    -  81.6826 per structural    -    3.255 per cycle
jsonexamples/random.json
|    Instructions : 498.5191 per block    (100.00%) -   7.7902 per byte    -  45.1809 per structural    -    3.278 per cycle
|    Instructions : 494.5467 per block    (100.00%) -   7.7281 per byte    -  44.8209 per structural    -    3.255 per cycle
jsonexamples/twitterescaped.json
|    Instructions : 557.9010 per block    (100.00%) -   8.7176 per byte    -  88.7182 per structural    -    2.575 per cycle
|    Instructions : 555.0234 per block    (100.00%) -   8.6726 per byte    -  88.2606 per structural    -    2.568 per cycle
jsonexamples/twitter.json
|    Instructions : 304.9666 per block    (100.00%) -   4.7654 per byte    -  54.4561 per structural    -    3.004 per cycle
|    Instructions : 301.6853 per block    (100.00%) -   4.7141 per byte    -  53.8702 per structural    -    2.964 per cycle
jsonexamples/update-center.json
|    Instructions : 350.7913 per block    (100.00%) -   5.4812 per byte    -  46.0815 per structural    -    2.815 per cycle
|    Instructions : 347.8345 per block    (100.00%) -   5.4350 per byte    -  45.6931 per structural    -    2.803 per cycle
```


My conclusion is that there is nothing to see as far as performance goes... at least on AMD Rome.

**Comment by jkeiser** [comment]
Yeah, I live in Washington state, which has a lot of people of Chinese origin who travel back and forth; we are hardest hit here, and are in near lockdown.

> I think that this PR does not change in any meaningful way the performance. I don't see anything concerning in the changes being proposed. At this point in time, this can be merged or not. I would leave it up to @jkeiser. The argument has to have to do with future work, I would think. Does this PR makes some upcoming changes easier or harder? It would take a deeper dive than I did to judge that.

The big thing it does right now is break stage 1 into three reasonably concrete, meaningful pieces (string recognition, token scanning, and token indexing), But I've been trying hard not to *just* do refactors, and obtain meaningful benefit directly from each one; so I'll see if any of my experiments get easier:

1. **Minification:** Identify true whitespace using `json_scanner`, and copy everything except the whitespace.
2. **Validate Only:** Do validation only, on top of `json_scanner` directly--don't produce a DOM. There's actually not a ton of stuff you have to do to validate JSON.
3. **JSON Token SAX:** Ultimately, I'd like to see SAX that yields up JSON tokens without validating or parsing them. Let the user decide what to do with it, provide them some easy interfaces to do things like parsing and validating it.
4. **Streaming Parse:** Run `json_scanner`, and instead of writing indexes, iterate over them in stage 2. One benefit is we can use escape data from stage 1 without paying a write penalty to communicate it between stages. This will take more thinking; the difficulty I'm having right now is that the stage 1 block-level loop means we have to build an iterator over two things (64-byte blocks, and then indexes in those blocks until thy are exhausted), which sounds expensive.

If these work, they could become the foundation for building user-driven streamed parsing, but that's super vague in my head, more a direction.

**Comment by jkeiser** [comment]
I'll say this: if the object split makes sense to you, if you can understand the edges between them and feel like they are reasonable abstraction levels to work with, I'll merge this as is. I have no issues with either of us changing things if we need it, but I don't want to check in a refactor without the other main person being prepared to think in and work with the abstraction.

**Comment by jkeiser** [comment]
I'll also say if you're not sure or don't have the energy to look, which would be totally understandable, then I'll just wait until I have a patch that qualitatively changes things on top of it.

**Comment by lemire** [comment]
Ok. I definitively have the energy and I will make the time.

My review was meant to cast things into what I believe is the proper light. This is about making the code more manageable. If it is not, it is not worth it.

**Comment by lemire** [comment]
The json_block design is a nice abstraction. The fact that it comes "for free" performance wise is neat.

**Comment by jkeiser** [comment]
> The json_block design is a nice abstraction. The fact that it comes "for free" performance wise is neat.

Yeah, it ends up packing some extra information in there (like escape characters), but since the optimizer destructures it, it can still independently figure out when we are (and aren't) using each piece.

**Pull request merged**
