### PR TITLE
Correct detection of NEON support

### LINKED ISSUE #389: jsonstream.cpp warning regarding an unused variable under ARM
```
src/jsonstream.cpp:194:14: warning: unused variable ‘supports’ [-Wunused-variable]
     uint32_t supports = detect_supported_architectures();
              ^~~~~~~~
```

### PR DESCRIPTION
**Pull request by mswilson**
... as the test as it is currently implemented will always evaluate to true.

Fixes #389

### CODE REVIEW

**Comment by lemire** [comment]
+1

I take it that there is no failing test?

**Comment by piotte13** [comment]
+1, nothing to add from my pov.

**Comment by mswilson** [comment]
I fixed the failing test from a previous revision of the change.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
