### PR TITLE
What about numbers?

### PR DESCRIPTION
**Pull request by lemire**

### CODE REVIEW

**Comment by jkeiser** [comment]
*facepalm*

**Comment by jkeiser** [comment]
Hrm, I thought I had a commit in there to remove write_tape_* from ParsedJson entirely. I must have done that in one of the side experiments :/

**Comment by lemire** [comment]
@jkeiser Gives us a change to examine this particular change in an isolated manner.

**Comment by lemire** [comment]
I see a substantial performance regression.

**Comment by jkeiser** [comment]
When I investigated, I thought I had found that templatization was the issue here, but maybe it wasn't! Maybe I forgot to change it back to call the visitor.

**Comment by jkeiser** [comment]
My theory, which probably applies here, was that something about its use in number parsing (possibly the fact that it was lexically distant) made the compiler forget that &pj was already in a register / in a certain place on the stack.

Oh.

It's worth checking what happens if you keep using pj directly in the never_inline functions, and don't even pass visitor ...

**Comment by lemire** [comment]
> It's worth checking what happens if you keep using pj directly in the never_inline functions, and don't even pass visitor ...

Removing the "never_inline" functions appear to solve the regression, so I think it is related to these functions, somehow.

**Comment by jkeiser** [comment]
Hypothesis: the compiler normally optimizes the entire visitor struct away. Having to pass a reference to the visitor to a real function makes the compiler turn it into a real thing, and bases all its other optimizations on that fact.

**Comment by jkeiser** [comment]
That probably explains why templatizing it kills perf, too.

**Comment by lemire** [comment]
> Hypothesis: the compiler normally optimizes the entire visitor struct away. Having to pass a reference to the visitor to a real function makes the compiler turn it into a real thing, and bases all its other optimizations on that fact.

Yes. So then we "really_inline" everything and hope for the best... would it work?

**Comment by jkeiser** [comment]
Maybe ... alternately, we can move all these methods to `ParsedJson` the way it is in your PR and I bet things would fall out better. Then we can do the parser / document separation separately, later.

**Comment by jkeiser** [comment]
(Making the latter change now, let's see what it does.)

**Comment by jkeiser** [comment]
Yep, performance recovers when you do that.

I pushed it to your branch, feel free to overwrite with --force if you have an alternate checkin. I think moving the methods to ParsedJson fixes it; even if it makes me feel icky, it's more important to separate these methods out from stage 2 than to get them in the exact right place.

**Comment by jkeiser** [comment]
And a refactor to split document from parser state is coming anyhow; we can revisit the split then.

**Comment by lemire** [comment]
Ok. Merge at will.

**Comment by lemire** [comment]
This potentially invalidates your theory that templates hurt the performance. It might be more a matter of encapsulation. If you encapsulate your code, you gain flexibility but you lose some performance. Normally, it would not matter, but we are bare metal folks here... :-)

**Comment by jkeiser** [comment]
What you say may be true, but IIRC the template hurt perf even if it was only on parse_number. Worth rechecking in case my brain misfired that too, though :)

**Comment by lemire** [comment]
@jkeiser My expectation is that templates come first in the compilation sequence, so there should never be a performance degradation...

In any case, there better not be because we are going to need templates at some point.

**Pull request merged**
