### PR TITLE
Replace macros with include files for better debugging

### PR DESCRIPTION
**Pull request by jkeiser**
The new macros make debugging really hard, at least on VS, because I can't get line #'s for compile errors. This fixes stage 1 with a technique that includes the same .h file multiple times, with different #defines, rather than using a macro.

I haven't had time to fix stage 2 as well, but wanted to get some testing on other platforms / thoughts.

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser That's an interesting approach.

@ioioioio : I think we should consider this alternate design.

**Comment by lemire** [comment]
Note: we are planning a 0.2 release soon. We'll need to decide whether we do away with our macros.

We discussed long and hard the macro route and we are quite aware of the downsides. If this approach helps maintainability and _debuggability_, without affecting performance, I think we need go for it.

**Comment by jkeiser** [comment]
I wouldn't block a 0.2 release on it, personally--it makes debugging easier for people working on the library, but it's not going to be a factor in the library interface.

Ultimately I think none of us want either multiple includes or macros; alas, the compiler!

This patch should be mergeable separately of stage 2 if it is the direction we want to go. I can't see how it could affect performance, as both are effectively preprocessor search and replace ... but "I can't see how it could affect performance" is usually famous last words.

**Comment by lemire** [comment]
Ok. Let us not block release 0.2 on this. 

@jkeiser : have you given some thought on how it interacts with the single-header version?

Note: I am not concerned by performance in this instance. Regressions are always possible, but the design by itself does not carry any performance penalty.

**Comment by jkeiser** [comment]
Regarding single-header, I would guess what we do is change [stripinc](https://github.com/lemire/simdjson/blob/master/amalgamation.sh#L67) to insert the relevant include instead when the include is on a list of particular headers (or perhaps anytime a header ends with `_impl.h`).

**Comment by TkTech** [comment]
Is this a regression in Visual Studio itself? Admittedly haven't used it in awhile, but the symbol files it generates (`.pdb`) have always had correct source line numbers even with wildly esoteric macros.

**Comment by lemire** [comment]
@jkeiser That's a good idea. Yes...

**Comment by lemire** [comment]
@TkTech  

My expectation is that macros are always more brittle than actual code... I take this issue as not being specific to visual studio... 

But your question is interesting in its own right... How clever can compilers get with macros?

**Comment by lemire** [comment]
@jkeiser Note that you have super unlucky with your PRs regarding conflicts. We do not enjoy messing with the code so widely. It just happened that you started working on simdjson just when several major changes were hitting the code base. Sorry.

**Comment by lemire** [comment]
I have removed this PR from the features needed for release 0.2.

**Comment by jkeiser** [comment]
@TkTech I don't know if it's a regression, but maybe it only applies to compile-time errors? There were compile errors in the multiline macro on VS, and VS 2017's "errors" window only showed me the line # for the caller. I spent a while binary-searching to find where the errors occurred :)

It's also kind of a pain to put backslashes on the end of each line ... but I wouldn't be nearly so worried about it if that were the *only* problem.

**Comment by ioioioio** [comment]
Just letting you know that I am working of this right now. I have successfully removed the macros from stage1_find_marks_macros.h. 
https://github.com/lemire/simdjson/tree/suppress_macros

Now I just struggle a bit with the amalgation, but I am very confident it will work.

**Comment by lemire** [comment]
Version 0.2.0 of simdjson was just released.

**Comment by lemire** [comment]
Thanks @ioioioio

**Comment by jkeiser** [comment]
Thanks tons @ioioio for the other patch; I'll close this in favor of #248

**Pull request closed without merging**
