### PR TITLE
Add failing test for a json with content zero

### PR DESCRIPTION
**Pull request by Licenser**
Add failing test for a JSON with a simple `0` in it for #131

### CODE REVIEW

**Comment by lemire** [comment]
Thanks.

**Comment by Licenser** [comment]
Added a fix too :) it's literally 1-bit difference :joy: damn computers being so picky on every bit.

**Comment by plokhotnyuk** [comment]
How about generation of test data?

**Comment by lemire** [comment]
@plokhotnyuk  If you mean randomized (fuzzed) tests... then I'd say it is a distinct issue. Certainly an important one,  but distinct...

**Comment by lemire** [comment]
Not forgetting this

**Pull request merged**
