### PR TITLE
single header contains local includes in some CI's only

### PR DESCRIPTION
**Pull request by DBJDBJ**
wanted to sort out local includes inside "simdjson" with "simdjson/" in front .. then I noticed some CI's are complaining ... see the image below with the apparent cause...

### CODE REVIEW

**Comment by DBJDBJ** [comment]
image

**Comment by jkeiser** [comment]
The singleheader version is generated by `make amalgamate`, which you can run locally. I changed it recently to find headers more dynamically, and perhaps that broke something?

I see both `#include "simdjson/x.h"` and `#include "x.h"` in the simdjson.h headers. You're right that we should really pick one.

**Comment by DBJDBJ** [comment]
In any case single header simdjson.h  including "simdjson/x.h " is not a good idea, I might be sure you would agree :) 

> I see both `#include "simdjson/x.h"` and `#include "x.h"` in the simdjson.h headers. You're right that we should really pick one.

If "x.h" and "y.h" are in the same folder, why not just include "x.h" :)

In the repo right now, single header simdjson.h does not contain local includes.  only those very few CI scripts have a problem ...

**Comment by lemire** [comment]
@DBJDBJ @jkeiser 

I am going to close this PR without merging. It fails our tests. If there is an issue with the headers, please submit a patch that passes our tests. Currently, I cannot reproduce any error with the amalgamation script. If there is an error, please suggest a test that exposes the bug.

**Comment by DBJDBJ** [comment]
@lemire what happens if you do this same simple change on your side?

**Comment by lemire** [comment]
The amalgamation script works and is part of the CI. If I make your proposed change then it breaks the build as you report. So we won’t break the build.

**Pull request closed without merging**
