### PR TITLE
Reduce exposed API surface

### LINKED ISSUE #478: Public jsonstream.h requires non-exposed src/jsoncharutils.h
`include/jsonstream.h` [requires jsoncharutils.h from `src/`](https://github.com/lemire/simdjson/blob/master/include/simdjson/jsonstream.h#L13), which is supposed to be implementation-only. We should either move the calling function to src/jsonstream.cpp, or move jsoncharutils.h (or part of it) into `include`.

### LINKED ISSUE #526: Rightsize simdjson.h/cpp
Right now, simdjson.h has a lot of parser-internal stuff. This makes it bigger than it needs to be, and also is potentially confusing to users perusing the headers looking for functionality (which does happen, even if you have docs).

We should get all parser internals--everything that is called only by methods in src/--into src/ somewhere, so that simdjson.h is as thin as we can make it.

Notes:
* User-facing inlines still need to be in include/simdjson/inline/, and that's OK.
* parser-internal *declarations* may livein simdjson.h when they are part of a public-facing class (such as document::parser).
* parser-internal classes and functions in simdjson.h should be in the `simdjson::internal` namespace where possible.
* parser-internal methods and fields should be marked private with appropriate `friend` declarations. If the friend class or function is parser internal, a forward declaration of the class may be used (don't bring the class into simdjson.h).
* parser-internal machinery in src/ should honestly be in `simdjson::internal` as well, so that including simdjson.cpp doesn't start presenting users with a bunch of public interface. Not as big a deal though.

They should be private where possible, and internal class and method declarations that have to be in simdjson.h should be in the `simdjson::internal` namespace so they are protected from discoverability.

### PR DESCRIPTION
**Pull request by jkeiser**
* Move isadetection.h to src/
* Move jsoncharutils.h to simdjson::internal namespace
* Move document::parser callbacks to src/
* Move user-called document function definitions to include/inline
* Remove reference to src/jsoncharutil.h from jsonstream.h (fixes #478)

Fixes #526.

### CODE REVIEW

**Comment by lemire** [comment]
We get includes that look like this...

```C++
 #include "simdjson/common_defs.h"
 #include "jsoncharutils.h"
 #include "simdjson/inline/document.h"
 #include "inline/document_parser_callbacks.h"
```

(I am not making this up, it is a direct copy-paste from actual code.)


I do not object, but I submit to you that some people might find this... chaotic-looking?

:-)

**Comment by jkeiser** [comment]
Yeah, and it would get a ton better if we just included simdjson.h from sec, which I guess there is no reason not to do now.

**Comment by jkeiser** [comment]
I'm also not opposed to either moving document callbacks up to top level src, or even back to include (though I really like the fact that people who use simdjson.h will get an error if they call parser callbacks they shouldn't be calling).

**Comment by jkeiser** [comment]
OK, I've fixed #include <simdjson.h> (which makes a big difference) and moved the single file out of inline. We can move it back in if we find ourselves doing a lot of inline implementations in src/, but for now, it's a little out of place.

**Comment by jkeiser** [comment]
Oh, you'll notice I used `#include <simdjson.h>` rather than `#include "simdjson.h"` here. I wanted to distinguish the fact that we're including something outside the current `src/` directory. `#include "..."` is now reserved entirely for documents in `src/`.

I didn't change the tests and such to use <>, because they will still end up as examples of how to use simdjson, and if you're doing the single header version, you will need to use "".

**Comment by lemire** [comment]
Ok. Looks good to me.

**Comment by jkeiser** [comment]
*sigh* figured out what happened here: turns out this merged into jkeiser/simdjson-h, not master. Will put up a PR and immediately push it.

**Comment by lemire** [comment]
> sigh figured out what happened here: turns out this merged into jkeiser/simdjson-h, not master. 

I did notice that, but I assumed it was deliberate.

**Comment by jkeiser** [comment]
Oh basing the patch against it was deliberate, but I was planing to switch the base to master after the other patch was merged, and forgot :)

**Pull request merged**
