### PR TITLE
Runtime dispatch

### PR DESCRIPTION
**Pull request by ioioioio**
These modifications implement the runtime dispatch for sse4.2 and avx2. It does so by checking the availability of some features for two minimal target architectures: Westmere or Haswell.

It works with GCC. Our tests show that it should also work with clang. However, for some mysterious reason, it does not (it won't compile). It needs to be fixed before the merge.

### CODE REVIEW

**Comment by lemire** [comment]
There are some tricky issues to complete this feature. If anyone wants to help review the code, please do. It works (well) with GCC. We need to complete the work.

When this PR will be merge, we'll have runtime dispatch without having to instrument the build: the dispatching is handled entirely in C++.

Ping @jkeiser @zbjornson @geofflangdale

**Comment by lemire** [comment]
Took me some time but I finally figured it out. The problem is that we keep switching back and forth with namespaces all over. If you drop the namespace, it works... but the namespace interfere.

As an aside the current PR has lots and lots of back and forth between the different ISAs which introduces more macros than needed.

Doing surgery.

**Comment by lemire** [comment]
Ok. I am stopping without having resolved the issue, aborting my changes.

The gist of the matter is that, under clang, you can't mix and match namespaces and pragmas. They interact badly.

**Comment by lemire** [comment]
Here is the problem:

```C++
// the following works fine under clang:
#pragma clang attribute push(__attribute__((target("sse4.2,pclmul"))), apply_to=function)
void f(){}
#pragma clang attribute pop


////////////
/// The following DOES NOT WORK: 'error: expected unqualified-id'
//////////
namespace joe {
#pragma clang attribute push(__attribute__((target("sse4.2,pclmul"))), apply_to=function)
void g() {}
#pragma clang attribute pop
}

int main() {
  g();
}

```

**Comment by lemire** [comment]
Here is the stackoverflow version...

https://stackoverflow.com/questions/57228537/how-does-one-use-pragma-clang-attribute-push-with-c-namespaces

**Comment by ioioioio** [comment]
well, that's embarrassing. I wonder how you found this.

The cis also show some problems with Visual Studio. I wonder what to expect with that one.

**Comment by jkeiser** [comment]
I'll run this under VS and see what I can see.

I wonder if the #pragma problem can be worked around by making a namespace per target and attaching the pragma to the namespace instead of the functions. Then the pragma at least exists at the same level as the caller.

**Comment by jkeiser** [comment]
In Visual Studio, the first build error appears to be related to a [lack of TARGET_REGION definition](https://github.com/lemire/simdjson/pull/227/files#diff-be2e7b500e6796935bc5d2fc3b664a64R13-R22) for VS. I'm not sure what the answer is (I'll see if I can find it, but no promises about doing it today or tomorrow). The specific error is:

```
1>C:\Users\john\Source\simdjson\include\simdjson/[simdutf8check.h(31,1)](https://github.com/lemire/simdjson/pull/227/files#diff-d130dca984283819e5bf4786d4d9954fR31-R33): error C4430:  missing type specifier - int assumed. Note: C++ does not support default-int
1>C:\Users\john\Source\simdjson\include\simdjson/simdutf8check.h(33,20): error C2448:  'simdjson::TARGET_REGION': function-style initializer appears to be a function definition
```

**Comment by lemire** [comment]
@ioioioio I have a version working under clang right now. Well. It builds.

**Comment by lemire** [comment]
And passes tests.

**Comment by lemire** [comment]
I created a new PR which appears to build on clang and gcc. However, the performance is not good (which may be a bug of some sort).

https://github.com/lemire/simdjson/pull/230

**Comment by lemire** [comment]
@jkeiser 

With clang you could maybe do an "apply_to=namespace" but I don't think this would work (I expect it is not supported for this kind of attribute). It would not work in GCC which has a more basic approach.

One approach I suggest is to avoid constantly changing targets within the same file. This makes the file very hard to read. So you probably want to regroup everything that concerns a given architecture in a big block. I think that this will have benefits regarding maintainability as well.

**Pull request closed without merging**
