### PR TITLE
Adding a flag which allows us to disable AVX detection. 

### PR DESCRIPTION
**Pull request by lemire**
This exposes a bug.

### CODE REVIEW

**Comment by lemire** [comment]
@jkeiser Can you have a look? It looks like on pre-AVX x64 hardware, UTF8 validation sometimes does not run (at least on short documents).

Embarrassingly, it appears we did not have any test for such cases.

**Comment by jkeiser** [comment]
Does this fix the issue or just make it possible to test?

Rather than a compile time flag it feels like this works better as a command line flag or environment variable: the `s` flag in parse.cpp forces SSE, assuming that's what this does (looks like it).

Not gonna say no to this since it makes things better, but compile time flags for runtime behavior worry me (means it's hard to know what exactly it is I'm running).

**Comment by jkeiser** [comment]
It may well be worth running this test against my genericization patch: given that it's running the same code for SSE and AVX, it might even fix the bug.

**Comment by jkeiser** [comment]
Here's the [force_sse line](https://github.com/lemire/simdjson/blob/52640518d3e2096a982d88850f811e51643fe999/benchmark/parse.cpp#L58) in parse.cpp.

We probably shouldn't merge this until we either have a fix or have a test that "expects" it to fail. I'll see if I can repro when I get time, but it might not be tonight, long day at work.

Note: just in case you're newish to being on this end of a code review (esp. in open source), I see code review as a conversation rather than a gate, It's also been a little over a decade since I was truly hip deep in industrial C++ code, so it's possible standards have changed or my intuition on The Best Ways To Do Compile Flags are rusted :)

**Comment by lemire** [comment]
>  just in case you're newish to being on this end of a code review (esp. in open source), I see code review as a conversation rather than a gate

I agree. This is my view as well.

**Comment by lemire** [comment]
> It may well be worth running this test against my genericization patch: given that it's running the same code for SSE and AVX, it might even fix the bug.

Good point.

**Comment by lemire** [comment]
I think that PR https://github.com/lemire/simdjson/pull/346 should be merged, and it may indeed fix the issue.

However, we need some way to test this in the future.

**Comment by lemire** [comment]
> I'll see if I can repro when I get time

We have independent reproduction of the problem, it is verified, real.

**Comment by lemire** [comment]
> Rather than a compile time flag it feels like this works better as a command line flag or environment variable: the s flag in parse.cpp forces SSE, assuming that's what this does (looks like it).

Yes but it comes at some expense in code complexity. With a compile-time flag, I can rebuild all of the tests with AVX2 disabled without changing any of the code.

If we try to generalize what is done in parse.cpp, we are going to increase substantially our code surface and worsen maintainability.

Another way to go would be to disable AVX via an environmental variable. This is easy but it is not perfect either... because environmental variables are not very visible... so if you have set, you may not remember to unset it, and then you may end up with hard-to-debug issues.

The best approach would be to run the code in Intel's simulator, but there are licensing issues that are unresolved: it is not clear whether we can legally use Intel's simulator in our CI without violating Intel's license. For obvious reasons, we would rather not do something that might be considered illegal according to Intel's lawyers.

There might be clever techniques, but I think what I am proposing here is not that bad.

Let us discuss it.

In any case, we need a way to test support on old processors.

**Comment by jkeiser** [comment]
Yep. I think there's a way to support runtime without much trouble (basically explicitly select architecture instead of calling find best architecture), but I'm fine with this approach until then. We do need a way to test.

**Comment by jkeiser** [comment]
@lemire went back here after merging the other patch and it let me resolve the Makefile conflict within the web editor. Let's see if it succeeds now.

**Comment by lemire** [comment]
Let us merge this... we can improve it later.

**Comment by jkeiser** [comment]
It fixed it. OK. Feel free to merge this, it's better to have it than not. While I think it'll be reasonable to allow explicit architecture selection at runtime, it's no reason to hold this up.

**Comment by jkeiser** [comment]
LOL that's a fun race condition :)

**Pull request merged**
