### PR TITLE
Remove templating for simd_input/utf8/strings, use struct for UTF-8 checks

### PR DESCRIPTION
**Pull request by jkeiser**
- Removes templating from simd_input, utf8_checker, and parse_string
- Does utf-8 checking in methods inside utf8_checker to cut down on out parameters

Something about the utf-8 changes (which might include the template) speeds things up a very tiny amount for some reason, which I didn't expect because even the order of code isn't changing; but it *might* be because I changed a bunch of methods from `inline static` to `really_inline`, and we've seen perf hits from `inline static` before. Regardless, that's not the reason for this; it gets rid of a bunch of indirection we didn't need.

### CODE REVIEW

**Comment by jkeiser** [comment]
This is failing utf-8 checks on ARM, but I can't see a reason why that would be in the code (i.e. this code should be identical, just less templated and more structified). I'll look when I can. Grr.

**Comment by lemire** [comment]
I can give you access to an ARM-based server.

**Comment by jkeiser** [comment]
Sure, that would be great! I'm at john@johnkeiser.com if you want to send something that way.

Meantime I'm making mechanical changes one by one and looking to see if CI passes :)

**Comment by jkeiser** [comment]
@lemire OK, it's fixed. I can't even figure out what I did wrong, but whatever it is, I'm not doing it anymore.

I also made drone run a bunch faster and arm in particular run more parallel, because I hate waiting for things :) I didn't improve clang on drone as much as I improved the gcc run, because I wasn't sure what the implications of running [this unofficial image](https://hub.docker.com/r/silkeh/clang) would be, but if we decide to go with that image, it runs SUPER fast and passes tests. It even has cmake thrown in for free!

**Comment by lemire** [comment]
@jkeiser Merge at will!

**Pull request merged**
