### PR TITLE
Create parser.parse_many() API

### PR DESCRIPTION
**Pull request by jkeiser**
This enables the document stream API (formerly JsonStream) mentioned in #516:

```c++
padded_string json = string("[1, 2, 3] true [ true, false ]");
document::parser parser;

// With exceptions
for (const document &doc : parser.parse_many(json)) {
  doc.print_json(cout);
}

// With error codes
for (auto [doc, error] : parser.parse_many(json)) {
  if (error) { cerr << "Error: " << error_message(error) << endl; exit(1); }
  doc.print_json(cout);
}
```

Note one change from the API in #516: this API lets you use `parse_many()` inline, in the for loop. If there is an error with allocation or anything else global, it will be yielded in the loop. Only one error will ever be yielded, after which iteration will stop.

This deprecates JsonStream as an API, but all the code remains intact in document:: stream.

I have not attempted to refactor or otherwise clean up the logic in JsonStream; this is entirely an API change.

### CODE REVIEW

**Comment by jkeiser** [comment]
A couple of further notes:

I did not allow parse_many with anything but padded string; it feels surprising that the API would copy my giant buffer by default, so I wanted to delay that decision by making the other versions private.

Also, note that the methods in JsonStream are private in document::stream. JsonStream exposes them, but normal document streams do not.

Finally, note that stream is forward only. Calling begin multiple times will not reset it. I don't know if that is taboo.

**Comment by lemire** [comment]
Originally, JsonStream could be "reset" and so rewinded, but though there was code for it, we did not have tests, and I suspected the code to be wrong, so I removed it. It would be easy to fix, but one needs to write tests.

**Comment by lemire** [comment]
We do have a benchmark, even if it is not great, for this code... `./parse_stream jsonexamples/amazon_cellphones.ndjson`. I think we can assume that the new API will not affect negatively the performance, but one might consider the possibility of updating the benchmark code with the new API to put numbers on the question.

Irrespective of performance concerns, I am all for merging this. It is a much better API.

**Comment by jkeiser** [comment]
@lemite I realized I hadn't properly documented the new API, either. Added docs, changed tests to use document::stream (I left a couple of tests to ensure the deprecated interface continues to work), along with changing the benchmark.

I modified parse_stream.cpp to use document::parse. The results are way too variable for me to make any conclusions, though, both before and after my change ... nothing stands out to me as issueful, but I can't really say!

**Comment by jkeiser** [comment]
Note: it turns out the new Drone CI amalgamated tests weren't updating amalgamated headers before running. Since they aren't presently required to be up to date, I'd rather CI do the right thing for people; I have updated the .drone.yml to run amalgamate before running amalgamated tests.

**Pull request merged**
