### PR TITLE
Add parser implementation interface and selection API

### PR DESCRIPTION
**Pull request by jkeiser**
This is the promised implementation selection patch, designed to simplify adding architectures and experimenting with new tape formats. Makes a couple of other things nice, too, and removes a bunch of code.

I think this was the last refactor needed to make experimental parsers easier. I suspect there's more needed on the usage side (think iterators) as we evolve towards a 1.0 API, but I think we've turned over all the big rocks that would affect parsing itself, sans a possible name change like `document` -> `json`.

### simdjson::implementation (parser implementation interface)

 This creates the [simdjson::implementation interface](https://github.com/lemire/simdjson/blob/jkeiser/virtual-arch/include/simdjson/implementation.h#L14-L126), representing a parser implementation for a particular architecture.

- It is implemented by [haswell](https://github.com/lemire/simdjson/blob/jkeiser/virtual-arch/src/haswell/implementation.h#L13-L24), [westmere](https://github.com/lemire/simdjson/blob/jkeiser/virtual-arch/src/westmere/implementation.h#L13-L20) and [arm64](https://github.com/lemire/simdjson/blob/jkeiser/virtual-arch/src/arm64/implementation.h#L13-L20)
- New architectures must implement parse, stage1 and stage2 and give a name/description
- Experiments and alternative parsers can be hung off this interface as new virtual functions, benefiting from architecture selection without affecting the public api
- `architecture` is removed, and templated functions using it are now virtual functions.

## simdjson::active_implementation (vtable implementation selection)

simdjson::active_implementation is a static pointer to the current implementation. Implementation selection becomes a single pointer swap.

- [Architecture detection](https://github.com/lemire/simdjson/blob/jkeiser/virtual-arch/src/implementation.cpp#L65-L73) is functionally unchanged, iterating through `available_implementations()` and taking the first one whose `required_instruction_sets()` are met.
- static function pointers for json_parse, find_structural_bits and unified_machine are removed in favor of the single vtable swap
- `parser.parse()` calls active_implenentation->parse() (or .stage1() / .stage2() for benchmarks and JsonStream).
- Default implementation detection happens in the wordy `detect_best_supported_implementation_on_first_use` implementation, which waits for a parse() or name() call, detects the best implementation, updates `active_implementation`, and delegates the call to that implementation.
- If the current CPU is unsupported, [unsupported_architecture](https://github.com/lemire/simdjson/blob/jkeiser/virtual-arch/src/implementation.cpp#L40-L58) is set as the active architecture, and returns `error_code::UNSUPPORTED_ARCHITECTURE` for all calls.
- Implementation selection is now a single pointer, which is atomic on ... well, more machines than multiple pointers are atomic on :)

### simdjson::available_implementations - explicit architecture selection and inspection API

Adds simdjson::available_implementations, which exposes the list of available compiled implementations for inspection and use.

- `simdjson::active_implementation = simdjson::available_implementations["westmere"]` selects the westmere implementation even if you're on haswell.
- `for (const implementation *impl : simdjson::available_implementations` iterates over available implementations.
- `simdjson::active_implementation.name()` prints the detected architecture name. `description()` is available too.
- See parse.cpp's ["-a westmere" switch](https://github.com/lemire/simdjson/blob/jkeiser/virtual-arch/benchmark/parse.cpp#L112-L119) and [dynamic help message](https://github.com/lemire/simdjson/blob/jkeiser/virtual-arch/benchmark/parse.cpp#L69-L73) for a good example.
- The actual implementation list is backed by a statically compiled array of pointers, down in `implementation.cpp`, so we both isolate the implementations and (hopefully) have zero initialization overhead for them.

### Miscellaneous

- I moved around the `document/*` headers and created `inline/*` instead. The headers were starting to get a headachy dependency graph; the typical way to resolve "I need to reference types from two headers" in C++ is to have the two headers *declare* their types, and put the functions in a third file including them both. `inline/*` is those files--inline implementations of class methods.
- I started using doxygen style comments on public interfaces. They aren't persistent everywhere, but you can see them on `implementation`. I also never actually integrated or ran doxygen, but we should think about that :)

## Perf

On intel at least, I don't see a difference (squinting at it, it looks like a small improvement). The caller benchmark on Kady Lake R consistently shows a small bump:

| Benchmark                    | PR      | master  |
|------------------------------|---------|---------|
| json_parse                   | 45.0 ns | 48.4 ns |
| parser_parse_error_code      | 45.0 ns | 47.8 ns |
| parser_parse_exception       | 44.7 ns | 47.8 ns |
| build_parsed_json            | 137 ns  | 148 ns  | 
| document_parse_error_code    | 142 ns  | 144 ns  |
| document_parse_exception     | 140 ns  | 146 ns  |

skylake-x and ampere aren't packing a high enough cmake to compile the call benchmark, but the overall numbers for `./parse jsonexamples/small/demo.json` are identical between master and virtual-arch on both machines.

## Performance Learnings

- `extern` global variables hurt performance, at least in this instance; making `active_implementation` an inline variable with initialization helped. It doesn't seem like it has anything to do with the actual initialization function; the one that's in there now is not inline.

## Concerns

- `json_parse` and `build_parsed_json` can be removed, and that would remove a lot of backcompat code along with several headers. I didn't do it because I wanted to limit the scope of these changes and also prove to myself backcompat was preserved. The only callers I've been changing up to this point, are callers who actually use internal interfaces (structural_indexes and direct calls to stage 1 / stage 2).
- I'd *like* the implementations to automatically sort and register themselves, so that we don't have to directly reference them in `haswell.cpp`, but given we only have 3, I felt like that was overcomplicating things for now :)
- I'm not actually sure the `parse` virtual function needs to exist; calling `stage1` and `stage2` directly probably yields the exact same perf, since we (I think) aren't inlining the two calls inside `parse`.

### CODE REVIEW

**Comment by jkeiser** [comment]
On my machine, the call numbers seem a veeeery teensy bit better (which I actually expect, not due to virtual functions but due to more careful `noexcept` and a few functions I swapped from non-inline to inlineable).

| Benchmark                    | PR      | master  |
|------------------------------|---------|---------|
| json_parse                   | 45.0 ns | 48.4 ns |
| parser_parse_error_code      | 45.0 ns | 47.8 ns |
| parser_parse_exception       | 44.7 ns | 47.8 ns |
| build_parsed_json            | 137 ns  | 148 ns  | 
| document_parse_error_code    | 142 ns  | 144 ns  |
| document_parse_exception     | 140 ns  | 146 ns  |

**Comment by jkeiser** [comment]
In other news, I would like to murder the EPYC machine that keeps failing out my PRs for perf.

**Comment by jkeiser** [comment]
Note: while looking over the Windows failure, I got kind of uncomfortable with the `implementation::*` statics living in the same class as the virtual methods, and also with how it felt to use the API with all those colons. So I made these changes:

* `simdjson::implementation::active() is now `simdjson::active_implementation`
* `simdjson::implementation::use(<impl>)` is now `simdjson::active_implementation = <impl>`
* `simdjson::implementation::available_implementations` is now `simdjson::available_implementations()`
* `simdjson::implementation::from_string(<str>)` is now `simdjson::available_implementations()[<str>]`

All the methods broker in pointers now, too, where before some of them did references and some pointers.

Hoping this fixes the Windows compile error too, fingers crossed.

**Comment by jkeiser** [comment]
Thank you sanitize, for saving the day :)

I now understand why we didn't detect on startup: static initializer order rears its ugly head when you least expect it. Even an array of pointers to static data gets filled in via a static initializer.

Changed it to use the same method as current: wait until the first actual parse call, detect the implementation, replace the vtable pointer, and get out of the way!

Windows is back to happy, and so is sanitize. Surely this shall be the final update.

**Comment by jkeiser** [comment]
Thank you sanitize, for saving the day :)

I now understand why we didn't detect on startup: static initializer order rears its ugly head when you least expect it. Even an array of pointers to static data gets filled in via a static initializer.

Changed it to use the same method as current: wait until the first actual parse call, detect the implementation, replace the vtable pointer, and get out of the way!

Windows is back to happy, and so is sanitize. Surely this shall be the final update.

**Comment by jkeiser** [comment]
I think this was the last of the big factoring rocks making experimentation harder. I hope :)

**Comment by jkeiser** [comment]
Success!

A note on code size: this pr removes more lines than it adds, and a lot of what it adds is comments. There is also some pending API deprecation to complete, and 3 or 4 more files that can be removed when that happens--json_parse and build_parsed_json are wrappers at this point.

**Comment by lemire** [comment]
I'll have a look soon!

**Comment by jkeiser** [comment]
A note: I think it's possible to preserve the function pointer method by dropping `virtual` and storing the function pointers in concrete `implementation` objects instead, effectively forming our own vtable. I just can't see that it would help us, and it loses us some magical compiler checks (and probably optimizations).

**Comment by jkeiser** [comment]
Super minor change: I [fixed](https://github.com/lemire/simdjson/pull/501/commits/b32bc7670307f0ce7992d34deb80b15b7199d7d0) the two concerns I wrote about (removed them from the description, copied them below). Performance remains unaffected. No more changes, really :) fuzzer machines do seem to be broken, though; I'll trigger them to re-run in a bit just in case.

> <strike>I don't like that `simdjson::active_implementation` is a raw, bare pointer. It is that way because I like the syntax, but we should probably wrap it, so that we can change how and where it's stored.</strike>

> <strike>I don't like that `simdjson::available_implementations` is the result of a function. I'd like to be able to call `simdjson::available_implementations["westmere"]` without the `()` in the middle. (Come to think, it should probably be uppercase since it's a constant, but same idea.) I think I did it while I was trying to deal with `extern`-related performance issues, but it is probably possible to change it back.

**Comment by lemire** [comment]
> I'm not actually sure the parse virtual function needs to exist; calling stage1 and stage2 directly probably yields the exact same perf, since we (I think) aren't inlining the two calls inside parse.

Right. If we worked on tiny inputs, we would want to have just one function call overall. But we are not (yet?) working on tiny inputs.

**Comment by lemire** [comment]
Given that @jkeiser promised not to make further changes, and given how many lines of code are affected, I am going to merge now, to avoid later conflicts.

**Comment by jkeiser** [comment]
One thing about the parse call, I guess, is that it was super easy to add now that we have this machinery :) I don't feel *bad* about it being there, I just don't think it's all that big a deal.

As noted, I'll follow up soonish to deprecate json_parse and build_parsed_json, so that we expose a single API to the world. (And again, while I do feel like APIs are kind of my jam, I won't feel bad at *all* if someone wants to put the brakes on that effort or flip it in a new direction.)

**Pull request merged**
