### PR TITLE
Fix minor problems

### PR DESCRIPTION
**Pull request by NewProggie**
Following is a first batch of smaller fixes concerning old style C-casts, const correctness, implicit casts and using delete functions wherever appropriate

### CODE REVIEW

**Comment by lemire** [comment]
The PR appears to fail on continuous integration tests. There are problem building the code. Can you check those out?

See in particular https://cloud.drone.io/lemire/simdjson/26/1/2

**Comment by lemire** [comment]
Looks fine. Let us wait for CI to run.

**Comment by NewProggie** [comment]
> Looks fine. Let us wait for CI to run.

Yes. I've noticed this issues already yesterday, but didn't had the time to get to it right away.

**Comment by lemire** [comment]
This now looks fine. This PR basically turns C-isms into C++-isms.

I'd feel better if someone else looked at this long list of (sensible) changes before I merged.  

Maybe @geofflangdale? Someone else?

**Comment by geofflangdale** [comment]
I've looked at this change list. It generally looks very good. The only thing I find unpalatable, in the non-pointer case, is turning conditions like "if (foo(x))" into "if (foo(x) != 0u)" - is there a reason that this rather verbose form is being used?

**Comment by lemire** [comment]
I spotted this as well. @NewProggie do you have a particular reason for the verbose "if (foo(x) != 0u)"? I don't think it is particular idiomatic, is it?

**Comment by NewProggie** [comment]
> I spotted this as well. @NewProggie do you have a particular reason for the verbose "if (foo(x) != 0u)"? I don't think it is particular idiomatic, is it?

Yes, that seems reasonable. I've updated this PR and re-added the implicit bool conversions

**Pull request merged**
