### PR TITLE
Runtime dispatch (version 3)

### PR DESCRIPTION
**Pull request by lemire**
This is a follow-up on  PR 227

https://github.com/lemire/simdjson/pull/227

This version appears to work on CLANG + GCC.

However, the performance is terrible.

cc @ioioioio

### CODE REVIEW

**Comment by lemire** [comment]
Note that amalgamation may not work yet.

**Comment by lemire** [comment]
Thanks to @jkeiser, it appears to work under Visual Studio.

**Comment by EgorBo** [comment]
@lemire I decided to update the full C# port of simdjson (the one based on `System.Runtime.Intrinsics`). Should I wait this PR or can work with the actual master? (it seems it should support both SSE and AVX and it should not be a problem to implement AVX/SSE switch with JIT).

**Comment by lemire** [comment]
@EgorBo I don't think so. I think this most useful for the wrapper.

**Comment by lemire** [comment]
This looks good except for the mysterious terrible performance...

**Comment by lemire** [comment]
Ah. Ok. The code was slow because in the `parse` executable, dispatching was only enabled for part of the test.

**Comment by lemire** [comment]
@ioioioio  Would you look at this PR?

**Comment by ioioioio** [comment]
Looks good. I was changing simddetection.h's name the other day (since now it does more), but it seems like I had not finished the job. Now it's done.

**Pull request merged**
