### PR TITLE
Minor code factoring: PUSH_SCOPE macro for { and [

### PR DESCRIPTION
**Pull request by jkeiser**
This just factors the code for pushing the current scope (start, object, continue) into a macro so it can be reused.

One learning: it matters a *lot* which side of that macro the write_tape() is on, and there is no one side that works everywhere. For the start array, it has to be *after* PUSH_SCOPE, and for object / array scope it has to be as early as possible, or there is a 1.5% loss of performance in stage 2.

### CODE REVIEW

**Comment by lemire** [comment]
And, of course, we get a performance regression warning.

Merging nonetheless.

**Comment by lemire** [comment]
Wait. There is a real error...
https://ci.appveyor.com/project/lemire/simdjson/builds/29833418/job/4tucii13s9hbnpbl

**Comment by lemire** [comment]
Oh. I see... I think that there might be missing code... I don't think you meant to write the following...

> #define SET_GOTO_CONTINUE(GOTO) pj.ret_address[depth] = (##RET_ADDRESS)[0];

This affects Visual Studio where we don't (and can't) use computed gotos.

What did you mean to put there?

**Comment by jkeiser** [comment]
@lemire the intent was to stringify the label and take the first character, which was equivalent to what happened before. However, I'm going to withdraw this patch, as I found a way to structure most of stage 2 into functions without regressing performance.

**Comment by lemire** [comment]
> However, I'm going to withdraw this patch, as I found a way to structure most of stage 2 into functions without regressing performance.

I badly want to see this!!!

**Comment by jkeiser** [comment]
[The PR is here!](https://github.com/lemire/simdjson/pull/430)

**Pull request closed without merging**
