### PR TITLE
[WIP] Fixing issue386

### PR DESCRIPTION
**Pull request by lemire**
This should fix issue 386

https://github.com/lemire/simdjson/issues/386

It seems to lower the stage 1 performance in some hasty tests. 

Needs to be reviewed.

### CODE REVIEW

**Comment by lemire** [comment]
This PR still has many issues. I will fix them.

**Comment by jkeiser** [comment]
Arch-specific bitmanipulation.h seems like the right approach!

**Comment by lemire** [comment]
@jkeiser 

I am basically pursuing your approach. I have weird performance issues, so I need to revisit everything... but this should be more maintainable.

I expect to be able to merge this today.

**Comment by lemire** [comment]
The PR currently has a significant regression during stage 2 on ARM. I am investigating.

(I was not expecting any difference.)

**Comment by lemire** [comment]
Hopefully I fixed the regression.

**Comment by lemire** [comment]
Green light!!!

**Pull request merged**
