### PR TITLE
Reduce parse API variants with flexible return types

### PR DESCRIPTION
**Pull request by jkeiser**
This reduces our various parse methods down to 2 major variants, `document::parse()` and `parser.parse()`, eliminating variants like `try_parse` by returning a more flexible result.

It enables these scenarios:

## Error Codes

```c++
// Parse and create a new document
auto [doc, error] = document::parse("[1,2,3]");
if (error) { exit(1); }

// Use the parser's internal document
auto parser = document::parser();
auto [doc, error] = parser.parse("[1,2,3]");
if (error) { exit(1); }

// Steal the document from the parser so you can store it elsewhere
auto [doc, error] = parser.parse("[1,2,3]");
if (error) { exit(1); }
document my_doc = doc; // take the document (doc is document&, not document)
```

## Exceptions

```c++
// Parse and create a new document
document doc = document::parse("[1,2,3]");

// Use the parser's internal document
auto parser = document::parser();
document &doc = parser.parse("[1,2,3]");

// Steal the document from the parser so you can store it elsewhere
document doc = parser.parse("[1,2,3]");
```

This reduces the number of `parse()` variants from 30 to 8, which makes me feel better :)

### CODE REVIEW

**Comment by lemire** [comment]
This looks very good (sexy). How is the performance... any effect?

**Comment by jkeiser** [comment]
I didn't check actually. I'll look through the benchmarks and see if there's a relevant one (`parse` isn't really designed to measure calling overhead, and doesn't call this method anyway since it splits up stage 1 and 2).

**Comment by DBJDBJ** [comment]
@jkeiser  you are doing good work and changing a lot of files. And you seem to understand the key concepts of valstat very well. Allow me to express few comments before I dive into the code :) 

As ever I might be pretty sure it is just terminology.

1. what is the `valstat` type you are using? I seem to remember this is discussed

```cpp
// very basic sketch
template <typename V, typename S>
struct valstat_template final {
  V * val;
  S * stat;
};
```
After which types can be defined. That type will slow down anything for approx 0 nano seconds.

2. That example above I would do differently

```cpp
// Parse and create a new document
auto [doc, status] = document::parse("[1,2,3]");
// key is there is no obuject called "error"
// error is just one of four states of an valstat intance
// communicated in code somewhat like this:
//  { {} , status }
// no value and yes status, ditto:
if ( ! doc ) { exit(1); }

// Use the parser's internal document
auto parser = document::parser();
auto doc  = parser.parse("[1,2,3]");
// { {}, stat }  was returned 
if (  ! doc.val ) { exit(1); }

// Steal the document from the parser so you can store it elsewhere
// on this "consuming site" I choose not to use structured binding
// doc is here an instance of some valstat type
auto doc = parser.parse("[1,2,3]");
if ( ! doc.val ) { exit(1); }
document my_doc = doc.val ;  // take the document (doc is document&, not document)
```
I am busy on the documentation branch.

**Comment by DBJDBJ** [comment]
@lemire @jkeiser 

I would like us not to throw anything from simdjson.

**Comment by jkeiser** [comment]
@lemire I'm working through a new benchmark (benchmark/bench_parse_call.cpp), but here's some results I got out of the exception path vs. error path vs. `build_parsed_json` and `json_parse` (existing APIs):

```
--------------------------------------------------------------
Benchmark                    Time             CPU   Iterations
--------------------------------------------------------------
document_parse_take        286 ns          285 ns      2357895
document_parse_try         302 ns          305 ns      2357895
build_parsed_json          279 ns          276 ns      2488889
parser_parse               116 ns          117 ns      6400000
parser_parse_try           112 ns          112 ns      5600000
json_parse                 109 ns          107 ns      6400000
```

`document.parse()` is in the same range of `build_parsed_json()`, and `parser.parse()` in the range of `json_parse()`, as expected--the originals might be a tiny bit faster, but it's not entirely clear.

@DBJDBJ the change should be more manageable to read now; it included commits from another PR which is now merged. Of course, that's caused a build error, but I'll deal with that separate.

The big reason for using the word `error` instead of `status` is that in this case, doc and error are mutually exclusive, and the word error is more specific (and therefore conveys more information) than status. And the big reason for checking `error` instead of `doc` is that most error-handling code is going to do `if (something) { cerr << error; }` (or something else that uses the error). It's weird to say `if (!doc) { cerr << error; exit(1); }` when what you wanted was to check for error a la `if (error) { cerr << error; exit(1); }`

Apart from that, I don't understand one change in your example: why do you use `auto doc = ...; if (!doc.val)` in your later examples instead of using `auto [doc, status] = ...; if (!doc)`? Is there some reason not to make the examples use the same form each time?

**Comment by DBJDBJ** [comment]
@jkeiser if I can read those results "exceptions" are faster than "error codes"?  Well, that would be a novelty for the C++ community at large :)   The way(s) to measure and compare exceptions vs no exceptions are based on comparing applications built with or without. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1640r1.html.

"valstatish" solution. Again, I might be wrong but you are returning: 

```cpp
class document::doc_result {
private:
  doc_result(document &&_value, error_code _error) : value(std::move(_value)), error(_error) { }
  doc_result(document &&_value) : value(std::move(_value)), error(SUCCESS) { }
  doc_result(error_code _error) : value(), error(_error) { }
  friend class document;
public:
  ~doc_result()=default;

  operator bool() noexcept { return error == SUCCESS; }
  operator document() {
    if (!*this) {
      throw invalid_json(error);
    }
    return std::move(value);
  }
  document value;
  error_code error;
};
``` 

Hardly an "error code" :) No wonder this is slow.  Among other things, 
in there you are keeping the copy of `document` and having the implicit casting operator from which you are moving the document out to the caller. Making it unusable for any next calls. This class is not 'error code' and certainly not a valstat.

the terminology and the concept -- the valstat behaviour exhibits four states 

```cpp
// return two optional values
// value and status 
// there is no 'special' return type visible
 auto [ value, status ] = function () ;
// four possible states
 if (   value &&   status )  { /* info */ }
 if (   value && ! status )  { /* ok   */ }
 if ( ! value &&   status )  { /* error*/ }
 if ( ! value && ! status )  { /* empty*/ }
```

The lack of value indicates an "error". "error" is a state not an object.  both value and status can be returned, that is not an error. example: HTTP returns consuming.

But, if you in your code want to call the state "error" you might as well do that.  In any case you do not need special method on that object to check if it is an error , it is enough to check for its existence or lack of. for example
```cpp
// valstat is returned
// both doc and error are simple pointers
auto [ doc, error ] = parser.parse("[1,2,3]");
if ( ! error  ) { /* all is fine */ }
 else { exit(1); }
```

> Apart from that, I don't understand one change in your example: why do you use auto doc = ...; if (!doc.val) in your later examples instead of using auto [doc, status] = ...; if (!doc)? Is there some reason not to make the examples use the same form each time?

This is because I wanted to show, structured binding is not mandatory. In your example, it is getting in the way:

```cpp
auto [people, error] = json::load("people.json");
if (error) { cerr << "Error loading people.json: " << error << endl; return error; }
auto [person, error] = people[1];
if (error) { cerr << "Error getting people[1]: " << error << endl; return error; }
auto [name, error] = person.get<string>("Name");
if (error) { cerr << "Error getting people[1].Name: " << error << endl; return error; }
auto [legs, error] = person.get("Legs", 2);
if (error) { cerr << "Error getting people[1].Legs: " << error << endl; return error; }
cout << "Name: " << name << ", Legs: " << legs << endl;
```
That will not compile and will be a pain to change, as you have righly noted. If you do it without structued returns binding things are suddenly simple:
```cpp
/// valstats are returned amd consumed
auto people = json::load("people.json");
if (! people.val) { cerr << "Error loading people.json: " << people.stat << endl; return ; }

auto person = people.val[1];
if (! person.val ) { cerr << "Error getting people[1]: " << person.stat << endl; return ; }

auto name = person.get<string>("Name");
if ( ! name.val ) { cerr << "Error getting people[1].Name: " << name.stat << endl; return ; }

auto legs = person.get("Legs", 2);
if ( ! legs.val ) { cerr << "Error getting people[1].Legs: " << legs.stat << endl; return ; }

cout << "Name: " << *(name.val) << ", Legs: " << *(legs.val) << endl;
```
That is the preffered way. No macros. Clean code.

Where do you want to go from here? I am here to help.

**Comment by jkeiser** [comment]
@dbjdbj note that there are two result classes. One is the one you mentioned, which is part of the "I want to trade efficiency for ease of use right now" document::parse API. That one *must* return a concrete value, because there is nothing else that could own the memory. The other is the result of document::parser::parse and returns a reference to a document owned by the parser object.

Away right now so can't do much responding, though :)

**Comment by DBJDBJ** [comment]
> @DBJDBJ note that there are two result classes. One is the one you mentioned, which is part of the "I want to trade efficiency for ease of use right now" document::parse API. That one _must_ return a concrete value, because there is nothing else that could own the memory. The other is the result of document::parser::parse and returns a reference to a document owned by the parser object.
> 
> Away right now so can't do much responding, though :)

I do sympathize,  but as in Indy Racing, one has to trade the comfort for the speed :)

I suggest we mail or chat,  to sort this out. Kind regards ...

**Comment by jkeiser** [comment]
We already have both of those interfaces--at any rate, it turns out different people make different choices :)

**Comment by jkeiser** [comment]
Here's the interface you probably actually care about:

* [json_parse](https://github.com/lemire/simdjson/pull/497/files#diff-8e15bdcb79f6057d83b4e6f385648a43R47) - this is the existing interface. It fills in a document owned by the `parser` object and returns an error code. No moves occur.
* [parser::parse](https://github.com/lemire/simdjson/pull/497/files#diff-8e15bdcb79f6057d83b4e6f385648a43R38-R39) - this is the replacement. It fills in a document owned by the `parser` object and returns a (document&, error) pair. No moves occur.

I believe [doc_ref_result](https://github.com/lemire/simdjson/pull/497/files#diff-d7c02545d9bd6d156b72246f9fda67deR286-R302) is less likely to trigger your performance concerns. But given that it doesn't make doc optional, I understand why referring to it as valstat-ish might cause confusion.

> if I can read those results "exceptions" are faster than "error codes"? Well, that would be a novelty for the C++ community at large :) The way(s) to measure and compare exceptions vs no exceptions are based on comparing applications built with or without. Please peruse this paper.

I'm really not trying to measure whether exceptions are faster here, and I don't need to be convinced that they are going to be slower overall :) I'm just trying to answer @lemire's performance question by measuring the overhead of the parse call, It seems like these interfaces are in the ballpark with the old ones (I don't trust the benchmarks to say much more than "ballpark" yet, especially with respect to exceptions).

**Comment by jkeiser** [comment]
OK. I've slimmed down the benchmark, particularly making the input a `const padded_string` to avoid the padding overhead. We're not *just* measuring call overhead, still, but we're getting a lot closer.

What it shows me:
* `parser.parse()`--the equivalent of the core function `json_parse`--has some overhead I didn't expect, given that it does nothing more than reformat the two outputs into a single one. I'd have expected the optimizer to do a better job.

  ```
  --------------------------------------------------------------------
  Benchmark                          Time             CPU   Iterations
  --------------------------------------------------------------------
  json_parse                      47.9 ns         47.4 ns     11200000
  parser_parse_error_code         54.2 ns         54.4 ns     11200000
  parser_parse_exception          54.2 ns         54.4 ns     11200000
  ```

* `document::parse()`--the equivalent of the "convenience method" build_parsed_json--and its equivalents have roughly the same extra overhead:

```
--------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
build_parsed_json                147 ns          146 ns      4480000
document_parse_error_code        150 ns          150 ns      4480000
document_parse_exception         150 ns          150 ns      4480000
```

I'll see if I can track down this overhead; I'm guessing a non-inline function got in there somewhere.

Note: @DBJDBJ's warning stands: this is *not* compiled with exceptions off. All we're measuring is the difference between the error_code path and exceptions path *in an executable compiled with the ability to do exceptions*. This shouldn't be taken as "users who use exceptions will be just as well off as users who don't."

**Comment by jkeiser** [comment]
@lemire it was indeed non-inline functions causing the overhead:

```
--------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
json_parse                      47.9 ns         47.4 ns     11200000
parser_parse_error_code         48.7 ns         48.8 ns     11200000
parser_parse_exception          47.7 ns         47.6 ns     14451613
```

```
--------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
build_parsed_json                147 ns          146 ns      4480000
document_parse_error_code        146 ns          143 ns      4480000
document_parse_exception         146 ns          146 ns      4480000
```

**Comment by lemire** [comment]
>  it was indeed non-inline functions causing the overhead

I fell off my chair!!! :-)

**Comment by jkeiser** [comment]
Just cleaning up the compiler errors I introduced when adding a Google Benchmark, now.

**Comment by jkeiser** [comment]
Google Benchmark doesn't pass cmake on the Ubuuntu 18 machines. I'm unsure why--the cmake version is the obvious thing to check, but I'm running the same cmake version on my machine. It also fails on sanitize. I've disabled the google benchmark compilation on those CI machines.

**Comment by jkeiser** [comment]
Aaand [that one CI machine](https://cloud.drone.io/lemire/simdjson/2260/2/2) is once again showing a perf degradation that I can't explain or really investigate. I looked back through the changes to json_parse itself, and I don't see anything that ought to have affected it. I have a feeling small variations in the compiler output (say, register names) are causing unpredicted outsized effects.

**Comment by jkeiser** [comment]
Aaand [that one CI machine](https://cloud.drone.io/lemire/simdjson/2260/2/2) is once again showing a perf degradation that I can't explain or really investigate.  My machine, skylake, skylake-x and ampere all show zero performance degradation, and code inspection does not indicate any reason existing methods should be either slower *or* faster.

I'm calling this baked, pending review.

**Comment by jkeiser** [comment]
(appveyor is having the same problem compiling Google Benchmarks as ubuntu 18--just turned it off there.)

**Comment by lemire** [comment]
Regarding the `parse` benchmarks, I see small variations in the number of cycles but nothing that is systematic or worrisome.

**Comment by lemire** [comment]
The new Google dependency adds increases the build time.

Master:

```
 cmake ..  -DCMAKE_BUILD_TYPE=Release
 time make 

 real	0m17.215s
user	0m15.788s
sys	0m0.940s
```

So about 17 seconds.

With this PR:

```
cmake ..  -DCMAKE_BUILD_TYPE=Release  -DSIMDJSON_GOOGLE_BENCHMARKS=ON
time make 
real	1m19.016s
user	1m14.076s
sys	0m3.420s
```

So almost 5 times longer to build.

**Comment by lemire** [comment]
It looks like the time necessary for the initial build is the same whether one does

```
cmake ..  -DCMAKE_BUILD_TYPE=Release  -DSIMDJSON_GOOGLE_BENCHMARKS=ON
```

or 

```
cmake ..  -DCMAKE_BUILD_TYPE=Release  -DSIMDJSON_GOOGLE_BENCHMARKS=OFF
```

And I think that when `-DSIMDJSON_GOOGLE_BENCHMARKS=...` is omitted, it defaults to OFF.

**Comment by lemire** [comment]
Regarding `benchmark/bench_parse_call`,  is there a flag to get instrumentation: cycles, branch predictions, instructions...? I find it hard to reason from a single number (running time). In this instance, we have what looks like flat numbers, but what if there were a difference...?

**Comment by lemire** [comment]
Regarding the code samples in the README, I think it would be prudent to have matching tests to ensure that the suggested code works (otherwise, it can be very frustrating for users).

**Comment by jkeiser** [comment]
> Are the new dependencies a step forward? They multiply by five the initial build time.

That's bad. I'll think it through, but my inclination is not to include the benchmark this go around. It proves to us that we haven't lost anything, but it's not something I expect to break every time we check in. We can then either work at getting gbench build times back to normal, or using other bench libs / revert to raw benchmarks.

> If one suggests code samples (in the README or elsewhere), one really ought to add corresponding tests because nothing irritates a programmer more than documentation that does match the actual software.

You are 100% correct. There are actually ways to write unit tests that run the documentation examples directly; I hate it when the README drifts from the tests, too :) I'll get one or the other in here.

> it is not supported at the legacy Makefile level

I feel like the right thing to do here is to make the Makefile generated from cmake, as I think we've talked about doing before ... but it's a valid concern, and causes confusion until that time. I don't think this is the only place we do it, though.

> apparently needs to be disabled in some instances in CI.

To be fair to them, this one is probably more my unfamiliarity with cmake causing me trouble debugging the issue :)

> When SIMDJSON_GOOGLE_BENCHMARKS is off (either because it is unspecified or manually set to OFF), I would expect the build to be faster... maybe five times faster?

Yeah, I am surprised about that one. I'll take a look.

> One thing that we really ought to have is instrumentation (cycles, instructions, misses): merely measuring the running time is not so useful.

It's definitely add-able. They've got a whole thing for custom metrics, designed for this.

> I tend to want to write my own benchmarking code, and my own instrumentation... because I like or I need to go deep. You can always do the instrumentation and the fine analysis using other tools, but, again, due to the specific focus of simdjson, I think we want, we need, very specific benchmarking tools...

You really do know more about it than everyone else here combined :) The reason I tend to reach for benchmarking libs is, my understanding is benchmarking has a lot of gotchas I don't know yet, and not having correct numbers to compare to, I won't even know that I've got it wrong.

The other reason is some of the benchmark libraries automagically give you nice graphs and statistics which have been vetted by, like, statisticians, and other quality of life features like comparisons over time. I know we can build it, and I'm quite sure you already have; it's mostly down to me not writing benchmarks every day for breakfast :)

**Comment by jkeiser** [comment]
Checked something in which gets rid of the vast majority of the build time difference. `cmake` still takes a while (an extra 10s) due to the extra ./configure tests it does, though. @lemire make sure when you are checking OFF vs. ON times you explicitly specify `-DSIMDJSON_GOOGLE_BENCHMARKS=OFF/ON`, or remove `CMakeCache.txt`, because it remembers the last choice you made otherwise :)

I'll work through the tests when I get my next moment.

**Comment by jkeiser** [comment]
Updated the README (honestly, it looks like I had started updating the README with aspirational goals and never updated it to what it actually was :)), Added readme_examples tests as well to validate that they work.

**Comment by jkeiser** [comment]
Link to the [updated README section](https://github.com/lemire/simdjson/blob/6f2f15bfba21a76ccaf7fdea127cdf5f749e91c8/README.md#code-usage-and-example).

**Comment by jkeiser** [comment]
I also turned the google benchmarks off by default until we decide what to do with them--you can still turn them on with -DSIMDJSON_GOOGLE_BENCHMARKS=ON

**Comment by lemire** [comment]
Ok. Let us merge, then... (please do so at your convenience)

I am not at all opposed to using a dependency for the benchmarks... but I will stick with the earlier statement: we need very fine/specific benchmarks.

Cheers!

**Comment by jkeiser** [comment]
Another thing I'd like to call out here: even though this modifies the README to match the API, I think it's still evolving. If we'd like a more stable README (and if the README is designed to work with the public release), I can totally go in for that and leave it as is until we feel like we've got a final 0.3 API. I'll merge for now just to get it out of mind, but changing it back is super easy and I'm willing.

> I am not at all opposed to using a dependency for the benchmarks... but I will stick with the earlier statement: we need very fine/specific benchmarks.

I hear you. I only have guesses what the *actual* benefit of a framework would be, either--the benefit could all be illusion.

I am curious though, if you have thoughts already: what kind of benchmarks tend to run badly on Google Benchmarks or other standard benchmarking frameworks? Are you talking about microbenchmarks that try to measure the effects of individual instructions or a small series of instructions? It feels like the `parse` style benchmarks could be done just fine in Google Benchmarks, including the instructions/cycles/etc., but I don't think that's what you mean by fine/specific :)

**Comment by lemire** [comment]
> I am curious though, if you have thoughts already: what kind of benchmarks tend to run badly on Google Benchmarks or other standard benchmarking frameworks? Are you talking about microbenchmarks that try to measure the effects of individual instructions or a small series of instructions? It feels like the parse style benchmarks could be done just fine in Google Benchmarks, including the instructions/cycles/etc., but I don't think that's what you mean by fine/specific :)


- We need to be able to benchmark specific steps in the code. Though this sounds trivial, this makes it hard to work with external frameworks like perf, xperf, vtune... That is, we often need to instrument the code itself to know precisely what we are measuring.
- We need to be able to control the number of iterations. This is often critical. If you are working with tiny inputs or large inputs, you want as few iterations as possible to deal properly with branches and cache. I frequently vary the number of iterations to see how the metrics behave. If they change with respect to the number of iterations, then I need to understand why.
- We need to be able to do the aggregates we need... for some problems, an average with a standard deviation is best... often times, a minimum is best, and so forth. So you really want access to the raw numbers.
- We need low-overhead measures.. That is, it is not acceptable for us to call the function many many times to make the overhead go away... because the number of iterations plays into the branch predictions and cache misses... 


Regarding quality of life... I run benchmarks all over the place, often on fresh installs... I just benchmarked the earlier CMake build on an ARM server, and I got over 5 mins to build simdjson... We definitively want to be mindful of the build times. I don't mind the gap between 10s and 20s, but going from 45 s to 5 mins is the difference with "ok" and "f*cking unbearable". Note that long build times negatively impact CI latency. It also harms the quality of life of some users who would like to contribute. I wouldn't say that build times are of primary importance, but it is also something that can strongly discourage you from working on the project.

**Comment by jkeiser** [comment]
I utterly agree we have to keep sane build times to keep ourselves sane. 5 minutes is ridiculous (I hadn't run a full make after cmake and didn't realize that was happening). Note that I did fix that, and the build times are not far off now--but taking dependencies does and always will increase build time, so we have to be mindful and selective.

**Comment by jkeiser** [comment]
I've read your points, and will keep them in mind. In fact, I'mma make an issue to evaluate Google Benchmarks and remove it from the benchmark I wrote if it doesn't make the bar, and link to this.

**Pull request merged**
