### PR TITLE
I think that i and idx should be of type size_t (64-bit).

### PR DESCRIPTION
**Pull request by lemire**
I think that this costs us nothing and makes the code future-proof.

### CODE REVIEW

**Comment by jkeiser** [comment]
@lemire one thing actually. Is there a reason `i` needs to be converted? I actually think `i` should be `int`. It's guaranteed to be in the range 0..64.

**Comment by jkeiser** [comment]
I have actually seen minor perf impact converting the result of intrinsic BMI functions from `int` to `unsigned`, as well (though it seems like it's not happening here?). OTOH, maybe adding uint64_t + int has perf issues, mandating this?

**Comment by jkeiser** [comment]
@lemire belay that, I was confused between this code and my experiment passing bits over. `uint32_t` is right, :+1.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
