### PR TITLE
Fixing potential mem leak.

### PR DESCRIPTION
**Pull request by lemire**
This is a fix for the problem reported in PR https://github.com/lemire/simdjson/pull/454

cc @DBJDBJ

### CODE REVIEW

**Comment by lemire** [comment]
@DBJDBJ This fixes the problem, right?

**Comment by DBJDBJ** [comment]
Is there anything wrong with the padded_string.h I have committed ? 

your code is also not right

image

you are freeing the object to be moved and then apparently swapping it. 

you need to swap first and then free.

Also always use `std::swap()` if you can.

**Comment by lemire** [comment]
@DBJDBJ I cannot merge the other PR. It appears to make many changes that I do not  understand and that are not related to the issue that the PR aims to fix (a potential memory leak).

Whatever the issue is, it should not require changing more than 5 lines of code.

**Comment by lemire** [comment]
> your code is not right

I understand what the current (master) move assignment can create a memory leak because we do not free the memory used by the current string before doing the assignation. I don't think it is practically a problem for us because the assignment is always used on an empty string, but it could be a serious problems for users. So we want to fix this.

It seems that all that is needed is to free the memory of the current string, and I think that's what this PR does. If I am wrong, and I might be, then I'd like an explanation and/or a demonstration.

> you can always use the std::swap function

The code you are proposing swaps and then sets half of the swapped value to nullptr/0. It seems unnecessarily complicated.

**Comment by lemire** [comment]
Let me put it this way: I want to avoid unnecessary changes to the code base.

We have many important design issues and new features to build, and I don't want us to be spending time on unnecessary changes.

You have identified real issues with simdjson, and please keep doing so... but if there is one memory leak in one function, we want to just fix this one function. If the function is 5 lines long, then the fix should not involve more than about 5 lines.

**Comment by DBJDBJ** [comment]
I do not want to impose anything but necessary changes, so I need to re-fork. As I am pressed for time I can not do this next few days.

Attached are drop-in replacements for `jsonioutil.h` and `padded_string.h`.  `jsonioutil.cpp` can be removed after that.

a padded string is streamlined and that mem leak is removed. please test and benchmark on your side.

[simdjson.zip](https://github.com/lemire/simdjson/files/4114033/simdjson.zip)

**Comment by lemire** [comment]
Thanks. For now I will merge this one-line PR as I think it fixes the memory leak you were alluding to and literally just changes one line. If you believe that there is still a bug after that, please provide an explanation and/or test so we can discuss further fixes.

**Comment by DBJDBJ** [comment]
ok, that should fix it, as I said I explained other details from my version, I think are also necessary, in that long comment above ... 
going forward I could add things to that performance bench you created (for get_corpus) so that we can see the gains or no gains...

**Comment by lemire** [comment]
Everything you wrote above sounds good.

Can you issue a PR on the swappable feature?

**Comment by DBJDBJ** [comment]
uh .. it is 22:24 here and I just managed to peek into here,  ...  when you do the next release, I will re-fork again and then start slowly from separate branches, etc ... I am not in a position now to contribute in a sane way :)

**Comment by DBJDBJ** [comment]
> This is a fix for the problem reported in PR #454
> cc @DBJDBJ

@lemire @jkeiser 

I suggest this re-opened quickly. Here is why. Basically I introduced a bug in rectifying a bug. Here is the now finally fixed  move assignment of `simdjson::padded_string`
```cpp
  // move assignment
  padded_string &operator=(padded_string && other_ ) {
    using namespace std;

    /*
    simdjson::aligned_free_char(other_.data_ptr);

    NO! the above done before std::swap CORRUPTS the heap!
    
    the std::swap() pointers overload is basically this:

      void swap(int *r, int *s)
      {
        int temp = *r;
        *r = *s;
        *s = temp;
        return;
      } 

    */
    // swap the native char * pointers , see the std algorithm above!! 
    // not leaking after std::swap of native pointers
    std::swap(data_ptr, other_.data_ptr);
    // swap the size_t value
    // in DEBUG mode most of the compilers set the moved from 
    // value to its 'zero' value
    std::swap(viable_size, other_.viable_size);

    // at this point other_ is unusable
    return *this;
  }
```
So whoever gets there first please do this change in the `padded_string`. My fork is currently unusable, and I am too busy. Sorry ...

**Pull request merged**
