### PR TITLE
Quick fix on stage1's performance regression

### PR DESCRIPTION
**Pull request by ioioioio**
This PR is a temporary fix to issue #258 (though it feels slower than v0.2.1, but it might be just my imagination). The macro removing has been reverted for stage1.

I might come with a complete fix tomorrow. I have [a branch](https://github.com/lemire/simdjson/tree/issue258_fix_performance) that works on x86, but won't compile or ARM64.

### CODE REVIEW

**Comment by lemire** [comment]
Thanks. We can pull out version 0.2.0 (`git checkout tags/v0.2.0`), compile parse as `parse0.2.0`, then run a comparison...

```
for i in jsonexamples/*.json; do echo $i; ./parse0.2.0 $i |grep "stage 1"; ./parse $i | grep "stage 1"; done
```

Result with your PR...

```
$ for i in jsonexamples/*.json; do echo $i; ./parse0.2.0 $i |grep "stage 1"; ./parse $i | grep "stage 1"; done
jsonexamples/apache_builds.json
stage 1 instructions:     327299 cycles:      96264 (47.17 %) ins/cycles: 3.40 mis. branches:        214 (cycles/mis.branch 449.60) cache accesses:       3467 (failure          0)
 stage 1 runs at 0.76 cycles per input byte.
stage 1 instructions:     327299 cycles:      96247 (47.87 %) ins/cycles: 3.40 mis. branches:        208 (cycles/mis.branch 461.17) cache accesses:       3594 (failure          0)
 stage 1 runs at 0.76 cycles per input byte.
jsonexamples/canada.json
stage 1 instructions:    6469871 cycles:    1946494 (24.68 %) ins/cycles: 3.32 mis. branches:       6294 (cycles/mis.branch 309.24) cache accesses:     121624 (failure       3808)
 stage 1 runs at 0.86 cycles per input byte.
stage 1 instructions:    6469871 cycles:    1940728 (24.64 %) ins/cycles: 3.33 mis. branches:       6312 (cycles/mis.branch 307.43) cache accesses:     121772 (failure       4531)
 stage 1 runs at 0.86 cycles per input byte.
jsonexamples/citm_catalog.json
stage 1 instructions:    4204799 cycles:    1267638 (50.04 %) ins/cycles: 3.32 mis. branches:        298 (cycles/mis.branch 4246.70) cache accesses:      78219 (failure        324)
 stage 1 runs at 0.73 cycles per input byte.
stage 1 instructions:    4204799 cycles:    1292475 (50.54 %) ins/cycles: 3.25 mis. branches:        333 (cycles/mis.branch 3878.98) cache accesses:      72442 (failure        258)
 stage 1 runs at 0.75 cycles per input byte.
jsonexamples/github_events.json
stage 1 instructions:     156318 cycles:      46048 (47.10 %) ins/cycles: 3.39 mis. branches:         12 (cycles/mis.branch 3752.62) cache accesses:        448 (failure          0)
 stage 1 runs at 0.71 cycles per input byte.
stage 1 instructions:     156318 cycles:      45934 (46.94 %) ins/cycles: 3.40 mis. branches:         10 (cycles/mis.branch 4401.99) cache accesses:        586 (failure          0)
 stage 1 runs at 0.71 cycles per input byte.
jsonexamples/gsoc-2018.json
stage 1 instructions:    6357969 cycles:    2034640 (53.53 %) ins/cycles: 3.12 mis. branches:       6073 (cycles/mis.branch 335.02) cache accesses:     126649 (failure       7449)
 stage 1 runs at 0.61 cycles per input byte.
stage 1 instructions:    6357969 cycles:    2031143 (53.31 %) ins/cycles: 3.13 mis. branches:       6117 (cycles/mis.branch 332.05) cache accesses:     119455 (failure       7294)
 stage 1 runs at 0.61 cycles per input byte.
jsonexamples/instruments.json
stage 1 instructions:     580785 cycles:     170002 (43.99 %) ins/cycles: 3.42 mis. branches:        340 (cycles/mis.branch 499.73) cache accesses:      10065 (failure          0)
 stage 1 runs at 0.77 cycles per input byte.
stage 1 instructions:     580785 cycles:     170000 (43.78 %) ins/cycles: 3.42 mis. branches:        349 (cycles/mis.branch 486.62) cache accesses:      10173 (failure          0)
 stage 1 runs at 0.77 cycles per input byte.
jsonexamples/marine_ik.json
stage 1 instructions:    9560970 cycles:    2908918 (24.36 %) ins/cycles: 3.29 mis. branches:       8512 (cycles/mis.branch 341.74) cache accesses:     187629 (failure      38755)
 stage 1 runs at 0.98 cycles per input byte.
stage 1 instructions:    9560970 cycles:    2973651 (25.45 %) ins/cycles: 3.22 mis. branches:       8254 (cycles/mis.branch 360.24) cache accesses:     182610 (failure      38578)
 stage 1 runs at 1.00 cycles per input byte.
jsonexamples/mesh.json
stage 1 instructions:    2214163 cycles:     635511 (22.16 %) ins/cycles: 3.48 mis. branches:        845 (cycles/mis.branch 751.66) cache accesses:      46868 (failure          5)
 stage 1 runs at 0.88 cycles per input byte.
stage 1 instructions:    2214163 cycles:     636038 (23.08 %) ins/cycles: 3.48 mis. branches:        854 (cycles/mis.branch 744.58) cache accesses:      46875 (failure          4)
 stage 1 runs at 0.88 cycles per input byte.
jsonexamples/mesh.pretty.json
stage 1 instructions:    4019167 cycles:    1161712 (30.71 %) ins/cycles: 3.46 mis. branches:         32 (cycles/mis.branch 35966.34) cache accesses:      75026 (failure        336)
 stage 1 runs at 0.74 cycles per input byte.
stage 1 instructions:    4019167 cycles:    1159670 (31.34 %) ins/cycles: 3.47 mis. branches:         32 (cycles/mis.branch 35355.82) cache accesses:      74999 (failure        316)
 stage 1 runs at 0.74 cycles per input byte.
jsonexamples/numbers.json
stage 1 instructions:     398430 cycles:     118398 (22.74 %) ins/cycles: 3.37 mis. branches:        368 (cycles/mis.branch 321.10) cache accesses:       5279 (failure          0)
 stage 1 runs at 0.79 cycles per input byte.
stage 1 instructions:     398430 cycles:     118705 (23.96 %) ins/cycles: 3.36 mis. branches:        411 (cycles/mis.branch 288.29) cache accesses:       6092 (failure          0)
 stage 1 runs at 0.79 cycles per input byte.
jsonexamples/random.json
stage 1 instructions:    1964079 cycles:     600216 (45.67 %) ins/cycles: 3.27 mis. branches:       1155 (cycles/mis.branch 519.33) cache accesses:      30337 (failure          1)
 stage 1 runs at 1.18 cycles per input byte.
stage 1 instructions:    1964079 cycles:     630784 (47.04 %) ins/cycles: 3.11 mis. branches:       1173 (cycles/mis.branch 537.59) cache accesses:      30320 (failure          0)
 stage 1 runs at 1.24 cycles per input byte.
jsonexamples/twitterescaped.json
stage 1 instructions:    1368707 cycles:     420872 (23.90 %) ins/cycles: 3.25 mis. branches:       1497 (cycles/mis.branch 281.05) cache accesses:      25869 (failure          1)
 stage 1 runs at 0.75 cycles per input byte.
stage 1 instructions:    1368707 cycles:     420891 (23.94 %) ins/cycles: 3.25 mis. branches:       1500 (cycles/mis.branch 280.58) cache accesses:      25873 (failure          0)
 stage 1 runs at 0.75 cycles per input byte.
jsonexamples/twitter.json
stage 1 instructions:    1743028 cycles:     535754 (51.21 %) ins/cycles: 3.25 mis. branches:       1522 (cycles/mis.branch 351.78) cache accesses:      29986 (failure          0)
 stage 1 runs at 0.85 cycles per input byte.
stage 1 instructions:    1743028 cycles:     541034 (51.63 %) ins/cycles: 3.22 mis. branches:       1520 (cycles/mis.branch 355.79) cache accesses:      29974 (failure          1)
 stage 1 runs at 0.86 cycles per input byte.
jsonexamples/update-center.json
stage 1 instructions:    1392620 cycles:     430473 (41.02 %) ins/cycles: 3.24 mis. branches:       2324 (cycles/mis.branch 185.22) cache accesses:      25924 (failure          0)
 stage 1 runs at 0.81 cycles per input byte.
stage 1 instructions:    1392620 cycles:     429653 (41.05 %) ins/cycles: 3.24 mis. branches:       2307 (cycles/mis.branch 186.23) cache accesses:      25927 (failure          0)
 stage 1 runs at 0.81 cycles per input byte.
```

Result with your current master...

```
$ for i in jsonexamples/*.json; do echo $i; ./parse0.2.0 $i |grep "stage 1"; ./parse $i | grep "stage 1"; done
jsonexamples/apache_builds.json
stage 1 instructions:     327299 cycles:      96320 (47.25 %) ins/cycles: 3.40 mis. branches:        213 (cycles/mis.branch 451.28) cache accesses:       4176 (failure          0)
 stage 1 runs at 0.76 cycles per input byte.
stage 1 instructions:     416822 cycles:     128624 (54.82 %) ins/cycles: 3.24 mis. branches:        371 (cycles/mis.branch 346.65) cache accesses:       3533 (failure          0)
 stage 1 runs at 1.01 cycles per input byte.
jsonexamples/canada.json
stage 1 instructions:    6469871 cycles:    1945981 (24.67 %) ins/cycles: 3.32 mis. branches:       6307 (cycles/mis.branch 308.54) cache accesses:     121516 (failure       4723)
 stage 1 runs at 0.86 cycles per input byte.
stage 1 instructions:    8052674 cycles:    2490734 (29.61 %) ins/cycles: 3.23 mis. branches:       5790 (cycles/mis.branch 430.13) cache accesses:     121513 (failure       4069)
 stage 1 runs at 1.11 cycles per input byte.
jsonexamples/citm_catalog.json
stage 1 instructions:    4204799 cycles:    1215118 (48.99 %) ins/cycles: 3.46 mis. branches:        291 (cycles/mis.branch 4171.36) cache accesses:      78107 (failure        251)
 stage 1 runs at 0.70 cycles per input byte.
stage 1 instructions:    5420495 cycles:    1616598 (55.44 %) ins/cycles: 3.35 mis. branches:        340 (cycles/mis.branch 4749.11) cache accesses:      77667 (failure        341)
 stage 1 runs at 0.94 cycles per input byte.
jsonexamples/github_events.json
stage 1 instructions:     156318 cycles:      46106 (46.54 %) ins/cycles: 3.39 mis. branches:         11 (cycles/mis.branch 4135.89) cache accesses:        774 (failure          0)
 stage 1 runs at 0.71 cycles per input byte.
stage 1 instructions:     202174 cycles:      61664 (54.01 %) ins/cycles: 3.28 mis. branches:         89 (cycles/mis.branch 689.39) cache accesses:        428 (failure          0)
 stage 1 runs at 0.95 cycles per input byte.
jsonexamples/gsoc-2018.json
stage 1 instructions:    6357969 cycles:    2033098 (53.69 %) ins/cycles: 3.13 mis. branches:       6083 (cycles/mis.branch 334.20) cache accesses:     119640 (failure       7168)
 stage 1 runs at 0.61 cycles per input byte.
stage 1 instructions:    8697897 cycles:    2888762 (62.01 %) ins/cycles: 3.01 mis. branches:       6018 (cycles/mis.branch 479.97) cache accesses:     126807 (failure       6960)
 stage 1 runs at 0.87 cycles per input byte.
jsonexamples/instruments.json
stage 1 instructions:     580785 cycles:     169910 (43.95 %) ins/cycles: 3.42 mis. branches:        333 (cycles/mis.branch 509.25) cache accesses:      10669 (failure          0)
 stage 1 runs at 0.77 cycles per input byte.
stage 1 instructions:     735738 cycles:     225555 (50.48 %) ins/cycles: 3.26 mis. branches:        596 (cycles/mis.branch 378.21) cache accesses:      10115 (failure          0)
 stage 1 runs at 1.02 cycles per input byte.
jsonexamples/marine_ik.json
stage 1 instructions:    9560970 cycles:    2906110 (24.34 %) ins/cycles: 3.29 mis. branches:       8528 (cycles/mis.branch 340.76) cache accesses:     177371 (failure      35455)
 stage 1 runs at 0.97 cycles per input byte.
stage 1 instructions:   11642794 cycles:    3654295 (29.62 %) ins/cycles: 3.19 mis. branches:       9583 (cycles/mis.branch 381.31) cache accesses:     177355 (failure      36243)
 stage 1 runs at 1.22 cycles per input byte.
jsonexamples/mesh.json
stage 1 instructions:    2214163 cycles:     645583 (22.50 %) ins/cycles: 3.43 mis. branches:        839 (cycles/mis.branch 768.94) cache accesses:      46928 (failure          1)
 stage 1 runs at 0.89 cycles per input byte.
stage 1 instructions:    2715914 cycles:     810418 (27.69 %) ins/cycles: 3.35 mis. branches:        976 (cycles/mis.branch 830.06) cache accesses:      46859 (failure          1)
 stage 1 runs at 1.12 cycles per input byte.
jsonexamples/mesh.pretty.json
stage 1 instructions:    4019168 cycles:    1160922 (30.65 %) ins/cycles: 3.46 mis. branches:         34 (cycles/mis.branch 33747.74) cache accesses:      69950 (failure        211)
 stage 1 runs at 0.74 cycles per input byte.
stage 1 instructions:    5128300 cycles:    1530051 (37.56 %) ins/cycles: 3.35 mis. branches:         61 (cycles/mis.branch 24758.11) cache accesses:      69014 (failure        247)
 stage 1 runs at 0.97 cycles per input byte.
jsonexamples/numbers.json
stage 1 instructions:     398430 cycles:     118528 (22.77 %) ins/cycles: 3.36 mis. branches:        370 (cycles/mis.branch 319.71) cache accesses:       6122 (failure          0)
 stage 1 runs at 0.79 cycles per input byte.
stage 1 instructions:     504018 cycles:     164114 (30.38 %) ins/cycles: 3.07 mis. branches:        479 (cycles/mis.branch 341.93) cache accesses:       5785 (failure          0)
 stage 1 runs at 1.09 cycles per input byte.
jsonexamples/random.json
stage 1 instructions:    1964079 cycles:     600759 (45.94 %) ins/cycles: 3.27 mis. branches:       1162 (cycles/mis.branch 516.99) cache accesses:      28340 (failure          1)
 stage 1 runs at 1.18 cycles per input byte.
stage 1 instructions:    2395104 cycles:     732818 (50.67 %) ins/cycles: 3.27 mis. branches:       1189 (cycles/mis.branch 616.01) cache accesses:      28131 (failure          1)
 stage 1 runs at 1.44 cycles per input byte.
jsonexamples/twitterescaped.json
stage 1 instructions:    1368707 cycles:     420517 (23.97 %) ins/cycles: 3.25 mis. branches:       1483 (cycles/mis.branch 283.39) cache accesses:      25853 (failure          0)
 stage 1 runs at 0.75 cycles per input byte.
stage 1 instructions:    1762939 cycles:     560291 (29.53 %) ins/cycles: 3.15 mis. branches:       2175 (cycles/mis.branch 257.54) cache accesses:      25612 (failure          0)
 stage 1 runs at 1.00 cycles per input byte.
jsonexamples/twitter.json
stage 1 instructions:    1743028 cycles:     535788 (51.52 %) ins/cycles: 3.25 mis. branches:       1523 (cycles/mis.branch 351.58) cache accesses:      28045 (failure          0)
 stage 1 runs at 0.85 cycles per input byte.
stage 1 instructions:    2219082 cycles:     689410 (57.54 %) ins/cycles: 3.22 mis. branches:       1674 (cycles/mis.branch 411.61) cache accesses:      27786 (failure          0)
 stage 1 runs at 1.09 cycles per input byte.
jsonexamples/update-center.json
stage 1 instructions:    1392620 cycles:     430679 (41.28 %) ins/cycles: 3.23 mis. branches:       2340 (cycles/mis.branch 184.01) cache accesses:      25914 (failure          0)
 stage 1 runs at 0.81 cycles per input byte.
stage 1 instructions:    1767578 cycles:     568490 (47.88 %) ins/cycles: 3.11 mis. branches:       2788 (cycles/mis.branch 203.89) cache accesses:      25768 (failure          0)
 stage 1 runs at 1.07 cycles per input byte.
```


Conclusion: Your PR fixes the regression.

**Comment by lemire** [comment]
So, to be clear, this PR is a potential fix for the regression.

**Comment by ioioioio** [comment]
I'm ok with this. It was just in case you considered it was urgent to provide a fix. In all cases, I am working for a real solution on top of it (since I could not find the cause of the regression).

**Comment by lemire** [comment]
It is not urgent since we don't have a broken release. The regression came after the latest release, so we are ok. We can take our time to fix this.

**Comment by lemire** [comment]
@ioioioio Maybe we want to drop this PR?

**Comment by ioioioio** [comment]
sure

**Pull request closed without merging**
