### PR TITLE
Parallelize Circle CI and speed up gcc runs

### PR DESCRIPTION
**Pull request by jkeiser**
This patch parallelizes our Circle CI jobs more, running the cmake variants in separate jobs instead of running them serially one after the other. It also speeds up gcc runs by starting from a well-known gcc:7 docker image rather than installing on top of Ubuntu. Finally, it uses some Circle CI 2.1 features to cut down on copy/paste a bit.

### CODE REVIEW

**Comment by jkeiser** [comment]
@lemire while I'm looking at this, there are kind of a lot of tests. Do you feel we need cmake tests for no-AVX and clang? If so, do we need all three variants (static, dynamic, sanitize) for no-AVX and for clang? I'm not sure if there are reasons beyond copy/paste :)

I would expect at a minimum:
* Full test run for gcc/AVX, gcc/SSE, clang/AVX, clang/SSE, without cmake involved
* Full test run for cmake static, dynamic and sanitize on gcc/AVX

Which would reduce the test combos down from 16 to 7.

This patch (when it works :) will make the tests run a lot more parallel, and for gcc at least, will run a bit faster using the premade gcc docker image instead of running apt-get on top of an ubuntu image.

**Comment by jkeiser** [comment]
In terms of this patch, I'd expect [the main workflow](https://github.com/lemire/simdjson/pull/280/files#diff-1d37e48f9ceff6d8030570cd36286a61R122-R141) to read:

```yaml
    jobs:
      - gcc-avx
      - gcc-sse
      - clang-avx
      - clang-sse
      - gcc-avx-dynamic
      - gcc-avx-static
      - gcc-avx-sanitize
```

**Comment by jkeiser** [comment]
@lemire I'll bite ... why do we use both circleci and drone? I see Drone has arm64, but what does CircleCI have that Drone doesn't?

**Comment by jkeiser** [comment]
@lemire aha! From [](https://github.com/lemire/simdjson/issues/56#issuecomment-466664536) this, it sounds like CircleCI has AVX-2, which is important for us. Presumably Drone doesn't? If that's the case then we'd still need Drone for ARM, unless Circle has something in that dept.

If Drone supports AVX-2 now, I'd drop Circle support. If not, I'd remove everything except arm64 from Drone just so we don't become a major contributing factor to global warming :)

**Comment by jkeiser** [comment]
Drone also says it supports Windows. Maybe could reduce everything down to one CI if so (still unsure if there are other differences that matter though, I've only ever used Travis myself).

**Comment by lemire** [comment]
@jkeiser Lots of questions here!

1. We need drone because it alone has ARM.

2. appveyor is used for Windows.

3. travis is effectively dead/unreliable. We can't rely on it at this time.

4. We could drop circleci.

5. We could drop appveyor and go with drone if we can get Windows support there.

6. These free CIs have a tendency to go away (like travis), as there is no clear business model behind them. The redundancy is a way to protect us against a disappearing CI.

**Comment by TkTech** [comment]
There's also the option of using the [Intel feature emulator](https://software.intel.com/en-us/articles/intel-software-development-emulator) to support running the tests on hosts without AVX2 (or anything else) if the reduction in ci complexity is worth it. Obviously we lose the ability to test for performance regressions (emulator will be _slow_), but these are hard to properly test on 3rd party ci anyways since you never know what machine you'll get or how busy the host really is.

**Comment by TkTech** [comment]
There's also Github's ci coming out of beta, which is really Azure Pipelines under the hood. It could handle both the x86_64 and Windows builds removing the need for circleci + appveyor.

**Comment by jkeiser** [comment]
@lemire the clang-sse-sanitize failure appears to be due to a network error. This should let us run the tests a lot more parallel and definitely speeds up the gcc tests (like a lot). I can make a separate PR to reduce it to just the tests I mentioned, so we can discuss that there.

Re appveyor / Windows, Drone *might* handle it, but I'm interested to see what Github comes out of the gate with.

**Comment by lemire** [comment]
@TkTech I have used the emulator locally (it was necessary to get the runtime dispatching to work) but I don't know how to use it with CI. Do you just download it from Intel each time?

**Comment by lemire** [comment]
@jkeiser  I have restarted the tests (presumably you also have this possibility).

**Comment by lemire** [comment]
@jkeiser I was going to write that Microsoft should offer Windows CI to open source projects... but I just remembered who owns GitHub.

**Comment by jkeiser** [comment]
@lemire oh! I hadn't realized I wasn't logged in on Circle. Yeah, I can restart tests in the future :)

**Comment by lemire** [comment]
All tests pass.

**Comment by jkeiser** [comment]
Rebased from master; I take it we're OK to merge if it's still green?

**Comment by lemire** [comment]
Amusingly perfcheck fails even though no code change occured.

**Comment by lemire** [comment]
Yes... do merge.

**Comment by jkeiser** [comment]
Hmm. I'll work up a 0.5% threshold ... one thing we didn't consider in the stats is that we're not running the tests 6 times, we're running them something like 48. Merging this, though.

**Comment by TkTech** [comment]
@lemire I just create a new docker image with the emulator tools already included, for personal use. A public image may or may not be against Intel's weird "What-If" license and its redistribution clause. I'm seeking clarification from the developer.

**Comment by lemire** [comment]
> I'm seeking clarification from the developer.

Thanks.

**Pull request merged**
