### PR TITLE
Trying to fix issue 465

### PR DESCRIPTION
**Pull request by lemire**
@eddelbuettel  Can you have a look?

This would fix https://github.com/lemire/simdjson/issues/465

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Yes, that looks like exactly what I had in mind. (And we could have discussed in #465 too, no?)

I am working off the `singleheader/` directory and have not found how to update it so strictly speaking I can't quite test yet.

**Comment by lemire** [comment]
Refreshing the single-header files.

**Comment by eddelbuettel** [comment]
Works like a charm (in a branch of RcppSimdJson) here with two changes:  
- copy both `simdjson.{h,cpp}` from the updated `singleheader/` directory of your `issue465` branch
- add a `-DSIMDJSON_NO_COMPUTED_GOTO` to `PKG_CXXFLAGS`

Now `R CMD check` is quiet about both recent issues (`stdout`, `GOTO`).  Many thanks!

There is one extremely low-hanging fruit we get to pick from seeing `R CMD INSTALL`:

```sh
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"  -DSIMDJSON_NO_COMPUTED_GOTO -I../inst/include -fopenmp -fpic  -g -O3 -Wall -pipe -pedantic  -c simdjson_example.cpp -o simdjson_example.o
In file included from simdjson_example.cpp:5:
../inst/include/simdjson.h:1647:2: warning: extra ‘;’ [-Wpedantic]
 1647 | }; // namespace simdjson
      |  ^
```

I very briefly looked for that and didn't immediately see where it came from in the expanded sources. I trust you do ...

**Comment by eddelbuettel** [comment]
Even better.  Two thumbs up from me.

**Comment by lemire** [comment]
Merging!

**Pull request merged**
