### PR TITLE
[WIP] Move UTF-8 checking to stage 2 (up to +15% throughput)

### PR DESCRIPTION
**Pull request by jkeiser**
This improves throughput by more than 11% overall on twitter.json on AVX2 Kady Lake R.

All files in `jsonexamples` got faster. Many were only 2-5% faster, but a number were in the 10-15% range, including twitter.json

The reasoning:

* **Do independent work in places with less CPU utilization:** Stage 2 has a lower instruction-per-cycle density than stage 1. UTF-8 checking likely soaks up more CPU than it can in stage 1, just by virtue of there being more CPU to soak.
* **Do mispredicts in places with less CPU utilization:** Correspondingly, stage 2's lack of congestion means it will generally find the mispredicting if statements quicker--there is much higher chance the if statement will be scheduled sooner just because the processor can't run quite as far ahead.
* **Clumping mispredicts together is good:** Stage 2 already mispredicts more often in general, so we will get much-reduced mispredict impact when two mispredicts happen in short sequence. If you're already mispredicting, you may as well do another mispredict right away!
* **Don't check if UTF-8 is valid outside strings:** UTF-8 outside of a string is invalid by virtue of not being `"`, `[]`, `{}`, `,`, `:`, `true`, `false` or a number. It is given a structural mark and will be rejected in stage 2 by the same logic that rejects `ture` and `~`. By processing utf8 in stage 2 during string parsing, we don't run full utf-8 validity checks for empty blocks or blocks with just numbers.  I doubt this affected twitter.json much, but there are files that will get at least some improvement here. Indeed, `random.json` gets about a 15% improvement
* **Make stage 1 less sensitive to ordering:** I'm sort of annoyed about this voodoo performance ordering dance I had to do, and this helps that--but I'm not yet sure if there's a broader principle here.
* NOTE: as implemented, this will process utf-8 checks once per string rather than once per block. This means if a 32-byte block (16 on Westmere) contains more than one string, it will do redundant UTF-8 checks. On the other hand, we use an unaligned load at the start of the string rather than doing it block by block, so strings that stretch across block boundaries may get away with fewer utf-8 scans. It's possible to optimize this by remembering the end of the last scan, but it's also unnecessary.

### CODE REVIEW

**Comment by jkeiser** [comment]
Given that it fails 2 of the UTF-8 checks, I have some investigation to do :)

**Comment by jkeiser** [comment]
OK, it turns out stage 2 was optimizing the utf8 check away and this is totally bogus :) I think there's something to it still--the fact that we're running the utf8 check over and over and over can't be good for business here :)

**Comment by jkeiser** [comment]
Oh! So basically after you eliminate escape characters. Yeah, that could rescue the performance of this.

**Comment by jkeiser** [comment]
While I was in there I noticed we're reloading the quote and backslash bits every time we hit a backslash. I'm being there is savings to be had there by clearing the bits as we use them, until they are empty. It still seems better to crunch the backslashes and write them out the first time we get them though, in stage 1.

**Comment by lemire** [comment]
> While I was in there I noticed we're reloading the quote and backslash bits every time we hit a backslash. I'm being there is savings to be had there by clearing the bits as we use them, until they are empty. It still seems better to crunch the backslashes and write them out the first time we get them though, in stage 1.

You are correct that we are probably handling backslashes in a suboptimal manner.

It is not clear to me how to do better at this time, however. You refer to this notion of "crunching the backslashes". Ok. So in stage 1, we do identify the backslashes that need to be "crunched" (whatever "crunched" means) but how do you do it?

You sketched it here:

https://github.com/lemire/simdjson/issues/228


Ok. So you write "single-character escapes yield single-byte replacements". Right. A single-character escape uses two bytes, and you must replace it with one byte. This means that you can, indeed, always do the processing "in situ" because escaping is always less space efficient...  And we have the information in stage 1.

In fact, in stage 1, we know exactly where the strings are, we know where the escapes are. It is clear we could do more... But how to do more is the tricky thing.

**Comment by jkeiser** [comment]
Heh, I was about to go put my new insights on the stage 2 from here, and realized that I have nothing new to add. Past me apparently knew things!

The only new thought is we might be able to do stage 2's escape/quote processing more efficiently by processing backslashes one SIMD width at a time instead of restarting after each backslash. It's not certain, though. Maybe the overhead of clearing backslash bits after processing them will end up worse the SIMD load and eq check. I've got a patch almost compiling, but I'm trying to take it easy for a few days, so it'll be a bit :)

**Comment by lemire** [comment]
I'm eager to read code that does escaping more efficiently.

**Pull request closed without merging**
