### PR TITLE
Handle a quote character within a unicode escape sequence

### PR DESCRIPTION
**Pull request by fwessels**
Properly detect a quote character within the hexadecimal unicode sequence and fail parsing of the unicode character.

This prevents potential reading beyond the end of the message buffer in case the invalid unicode character is the last element of the JSON message and no further quotes are found before the end of the message.

Examples of such messages are:

{"":"\u20A"}

or

{"":"\udbff\u123"}

(see fail76/fail77.json)

### CODE REVIEW

**Comment by lemire** [comment]
For some unclear reason, the fuzzers do not like this PR.

**Comment by fwessels** [comment]
We found it actually with a fuzzer in the Golang port. 

Disabling the code still allows the two new fail test cases to pass, presumably since it will find a quote somewhere in memory after reading past the end of the message...

**Comment by lemire** [comment]
I created a new PR that adds just the two new test files 

https://github.com/lemire/simdjson/pull/415

Before doing some code changes, we should verify that there is a bug. Let us see what CI tells us.

**Comment by lemire** [comment]
Note that on my machine, I cannot verify the existence of a bug.

**Comment by fwessels** [comment]
Here is the original bug from the Golang port (and corresponding testcase): https://github.com/fwessels/simdjson-go/issues/33 

It is reported as “written beyond slice capacity” because parse-string() keeps on copying to the String buffer until it finds the first quote. (And the written beyond slice capacity is reported on the String buffer, not the message buffer, although we will also read beyond the end of its buffer)

Since upon encountering a \u four bytes are unconditionally read, the closing quote is missed and the function will keep on copying until it detects a quote somewhere in memory.

**Comment by fwessels** [comment]
See also https://github.com/fwessels/simdjson-go/blob/master/parse_string_test.go

 Note that the testcase also fails without the fix, but if you were to inspect the string buffer you will see that the string (containing the erroneous Unicode char) has not been copied out correctly (or too much in effect, possibly beyond the end of the buffer)

**Comment by lemire** [comment]
I have checked in the files from this PR through another PR. It passes our tests.

@fwessels suggests that there might be some kind of buffer overrun, but I could not verify it. Of course, the bug may still be out there, but we would need a failing test.

Can anyone provide a way to reproduce a failing test?

**Comment by jkeiser** [comment]
I don't believe simdjson has this issue. Totally willing to be proven wrong, I'm doing code inspection rather than actual tests.

In simdjson, [parse_string returns early](https://github.com/lemire/simdjson/blob/master/src/generic/stringparsing.h#L59) when it detects a non-hex character in \uXXXX. Looking at [the simdjson-go commit to fix this problem,](https://github.com/fwessels/simdjson-go/commit/f23a7968c87532ddcfd46119ca5c46e8a473d7da), simdjson-go wasn't returning early on error, and was fixed to do so.

If one were testing to find issues, one might try putting all possible invalid values into each of the \uXXXX spots, and look for accidentally-valid values returned by [`hex_to_u32_nocheck`](https://github.com/lemire/simdjson/blob/7bde23590a1f24add904a2b4be4ab50b0d227037/src/jsoncharutils.h#L252-L255). On visual inspection, the tables look right to me.

**Comment by lemire** [comment]
On @jkeiser 's recommendation, I am closing this issue.

**Comment by fwessels** [comment]
It looks like bad unicode characters are detected during stage 1, so therefore stage 2 would never see the issue. So the fix does not apply to simdjson.

**Comment by jkeiser** [comment]
Note that simdjson won't detect bad \u in stage 1, just bad raw utf8.

**Pull request closed without merging**
