### PR TITLE
Add doxygen docs

### PR DESCRIPTION
**Pull request by jkeiser**
This adds `make api/docs` to our repository (requires doxygen) which creates api/docs/index.html.

[See docs preview here](https://htmlpreview.github.io/?https://github.com/lemire/simdjson/blob/jkeiser/doxygen/doc/api/html/index.html).

I also went through and tried to prune down to the public interface, but I may have missed things :)

### CODE REVIEW

**Comment by lemire** [comment]
I am fine for us to merge this, but I'd like to bring one point before we do. You were unhappy not long ago about the fact that the single-header version could get out of sync with the code. 

If we check in the doxygen documentation, it is the same problem (same type of problem). Because the doxygen output is basically HTML, it is relatively convenient to post it elsewhere. We could easily create a static site and update it with the doxygen content periodically.

Note that I *favor* pulling in this PR. I just want us to think it through.

**Comment by jkeiser** [comment]
I agree. Actually, on that note, perhaps the best first step is to check in the makefile and doxyfile, but not the actually l actual docs. We can generate those automatically somewhere.


This pr is mainly important because it gives us a clear way to declare and document our public API.

**Comment by lemire** [comment]
Holding on before merging this so that we can decide on whether to check in the HTML files.

If we don't check them into GitHub, I will volunteer to somehow host the HTML files on some server.

(Several observant folks may have notice that we still don't have a simdjson web site. Needing a place to put the doxygen files would be good motivation to create such a site.)

**Comment by jkeiser** [comment]
This is also based on the DOM navigation API patch (#510), since there was a lot of documentation in there, so it's blocked on that too :)

**Comment by jkeiser** [comment]
I've rebased and removed the bit that checks in the HTML files. I agree we shouldn't check in generated content.

**Comment by jkeiser** [comment]
@lemire we can use github pages if we want. There are even prebaked github actions to generate doxygen and publish to github pages: https://github.com/seanmiddleditch/gha-publish-to-git

**Comment by jkeiser** [comment]
I wouldn't block this on it--this gives us some nice updated docs--but it seems like it might be pretty easy.

**Comment by lemire** [comment]
Merge at your earliest convenience.

**Comment by jkeiser** [comment]
This accrues towards solving #293.

**Comment by jkeiser** [comment]
Christ on a muffin, I didn't merge this either.

**Comment by jkeiser** [comment]
Merged.

**Comment by lemire** [comment]
> Christ on a muffin

As a non-native English speaker, this one took me by surprise.  I have been trying to figure out the origin of the expression, but...

**Comment by jkeiser** [comment]
It's possible I made it up, but I think I've heard it before: it likely has to do with people saying there's a miracle because they see Jesus's face in watermelons, toast, etc.

**Pull request merged**
