### PR TITLE
Adding a "get_corpus" benchmark.

### PR DESCRIPTION
**Pull request by lemire**
We have a PR that proposes to streamline the get_corpus function, but we have no benchmark. Let us create one.

### CODE REVIEW

**Comment by lemire** [comment]
Copying the filename is trivial in this instance compared to the cost of loading up the file's content.

**Comment by DBJDBJ** [comment]
> Copying the filename is trivial in this instance compared to the cost of loading up the file's content.

That is true. That was a general remark for why simdjson should use `std::string_view` function arguments, everywhere.

I also think (now that I have made it 'Swappable'), `simdjson::padded_string` would be pretty fast as value-based argument.

**Comment by lemire** [comment]
When benchmarking, we have to worry that the compiler might optimize away much of the work. The swap prevents the compiler from getting too clever because the data escapes the function.

**Comment by DBJDBJ** [comment]
image

this "new  no exception" get_corpus has not made much performance gains

**Pull request merged**
