### PR TITLE
Make dynamic dispatch free of TSan warnings

### PR DESCRIPTION
**Pull request by vitlibar**
https://github.com/lemire/simdjson/issues/251
https://github.com/yandex/ClickHouse/issues/6285#issuecomment-517970722

### CODE REVIEW

**Comment by lemire** [comment]
Great.

**Comment by lemire** [comment]
The current plan is to merge this and quickly issue a new release.

In the worst case, I expect that this PR should only bring a few dozens cycles of penalty... We should check that this is the case.

**Comment by jkeiser** [comment]
I do wonder if any of the many CI solutions out there handles perf regression checks. I have to imagine it's doable.

At the *very* least, we could do a CI run that benches the code before and after the patch in the same container.

**Comment by lemire** [comment]
This is being held until https://github.com/lemire/simdjson/issues/258 is solved so we can assess performance issues sanely before merging.

Note: no performance regression is expected.

**Comment by lemire** [comment]
I verified that there is no visible performance regression.

I'll add @vitlibar to the contributors.

**Pull request merged**
