### PR TITLE
 Fix C4146 build error on UWP with MSVC 

### PR DESCRIPTION
**Pull request by myd7349**
Hi! I am trying to add `simdjson` to `vcpkg` recently: https://github.com/Microsoft/vcpkg/pull/5509

There is a C4146 error with the `x64-uwp` triplet(vcpkg install simdjson:x64-uwp):

>7>e:\vcpkg\buildtrees\simdjson\src\b2f096a4ff-3604fbb5d0\include\simdjson\numberparsing.h(334): error C4146: unary minus operator applied to unsigned type, result still unsigned (compiling source file E:\vcpkg\buildtrees\simdjson\src\b2f096a4ff-3604fbb5d0\src\stage2_build_tape.cpp) [E:\vcpkg\buildtrees\simdjson\x64-uwp-dbg\src\simdjson.vcxproj]

This patch try to fix this problem.

### CODE REVIEW

**Comment by lemire** [comment]
You surely did not mean to replace bytes by butes...?

**Comment by lemire** [comment]
Other than that, this looks fine.

**Comment by lemire** [comment]
@myd7349 I think you introduced a typo: butes. Can you fix it before I merge?

**Comment by myd7349** [comment]
@lemire Sorry for the delay!

It seems that the typo in the single header version is fixed in: https://github.com/lemire/simdjson/commit/c1dea29501360a58e18be59a81f56cc09762c50c. But the original typo in `parsedjson.h` was not fixed. So once I run `amalgamation.sh` again, the typo will come back again.

I have fixed the original typo in `parsedjson.h` and regenerate the single header again.

**Comment by lemire** [comment]
Merging.

**Comment by myd7349** [comment]
@lemire Thanks! I will update the PR under vcpkg tomorrow.

**Pull request merged**
