### PR TITLE
SEGFAULT bug fix in parse_string

### PR DESCRIPTION
**Pull request by technateNG**
PR with fix to Issue #148.

### CODE REVIEW

**Comment by lemire** [comment]
Thanks. Could we catch this in stage 1 and avoid the added check with each string?

I’ll work on it.

**Comment by geofflangdale** [comment]
Good catch, but the solution could be more efficient.

We already detect whether we're in a quoted pair continuously in the loop in stage 1. We should be able to tell if we're in quotes by looking at prev_iter_inside_quote inside find_structural_bits.

Stupidly, I had a checklist to look at that but didn't apply it, which goes to show that checklists are only useful if you actually consult them.

**Comment by technateNG** [comment]
I pushed additional commit to fix issue in first stage. All tests passed. My set of invalid inputs passed too.
My first assumption is that valid string in json always should have even number of quotes (two). 
Algorithm counts number of set bits in quote_bits integer and summarize them in every loop pass. After loop - value is checked. When is even than this check passes otherwise function returns false.

Counting set bits is realized in 4 bit sections and stored array of precalculated results. It's possible to increase sections to lower amount of loop passes.
I'll add my test cases to tests.

**Comment by geofflangdale** [comment]
I still think this solution is too elaborate and expensive. My gut feeling is that all such problems would be eliminated if, once the loop and the final iteration cleanup code ends in find_structural_bits, we check that prev_iter_inside_quote is 0 (if it is not, it will be an error). This variable is set to an all-1 pattern if the previous iteration leaves us inside a quote pair, and thus should be 0 when the main loop ends.

Please refer to the quote detection code if this isn't clear: https://github.com/lemire/simdjson/blob/master/src/stage1_find_marks.cpp#L221-L258

Unless I'm making a mistake, this simple test should catch your case.

**Comment by technateNG** [comment]
Yes. I overthinked that. Pushed PR. All test cases pass.

**Pull request closed without merging**
