### PR TITLE
Export CMake targets

### PR DESCRIPTION
**Pull request by myd7349**
This patch is part of https://github.com/Microsoft/vcpkg/pull/5509 .

### CODE REVIEW

**Comment by lemire** [comment]
Let us merge!

**Comment by myd7349** [comment]
@lemire Thanks! :-)

**Comment by lemire** [comment]
@myd7349  Did it help?

**Comment by myd7349** [comment]
@lemire Yeah! I am able to remove the patch file used in the portfile now: https://github.com/Microsoft/vcpkg/pull/5509/commits/4327f4d82cc1e402794b145eb0d95f921277a71c

**Pull request merged**
